[package]
name = "kinetic-test"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kinetic-core = { path = "../kinetic-core" }
kinetic-network = { path = "../kinetic-network" }
kinetic-vdf = { path = "../kinetic-vdf" }
kinetic-storage = { path = "../kinetic-storage" }
libp2p = { workspace = true, features = ["tokio", "tcp", "noise", "yamux", "dns", "kad", "request-response", "macros", "gossipsub"] }
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
kinetic-nrs = { path = "../kinetic-nrs" }
hickory-client.workspace = true
hickory-server.workspace = true
hickory-proto.workspace = true
bytes.workspace = true
reqwest.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
kinetic-primitives = { path = "../kinetic-primitives" }
axum.workspace = true
ed25519-dalek = { workspace = true, features = ["rand_core"] }
rand_core = { workspace = true, features = ["getrandom"] }
