[package]
name = "kinetic-test"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kinetic-core = { path = "../kinetic-core" }
kinetic-network = { path = "../kinetic-network" }
kinetic-vdf = { path = "../kinetic-vdf" }
kinetic-storage = { path = "../kinetic-storage" }
libp2p = { workspace = true, features = ["tokio", "tcp", "noise", "yamux", "dns", "kad", "request-response", "macros", "gossipsub"] }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
kinetic-nrs = { path = "../kinetic-nrs" }
hickory-client = "0.24"
hickory-server = "0.24"
hickory-proto = "0.24"
bytes = "1.12.1"
reqwest = "0.13.4"

[dev-dependencies]
serde_json = "1.0"
tempfile = "3.2"
kinetic-primitives = { path = "../kinetic-primitives" }
axum = "0.8.9"
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
rand_core = { version = "0.6", features = ["getrandom"] }
