[package]
name = "kinetic-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Concrete persistent storage implementations for the Kinetic Network, utilizing Redb natively and OPFS for WASM."
readme = "README.md"
repository.workspace = true

[dependencies]
bytes.workspace = true
kinetic-core = { path = "../kinetic-core" }
tracing.workspace = true

[dev-dependencies]
proptest.workspace = true
tempfile.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
redb = "4.2.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.127"
wasm-bindgen-futures = "0.4.77"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = [
    "FileSystemDirectoryHandle",
    "FileSystemFileHandle",
    "FileSystemGetFileOptions",
    "FileSystemReadWriteOptions",
    "FileSystemSyncAccessHandle",
    "Navigator",
    "StorageManager",
    "Window"
]
