[package]
name = "kinetic-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kinetic-core = { path = "../kinetic-core" }
sled = "0.34"
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
bytes = "1.6.0"

[dev-dependencies]
tempfile = "3.27.0"
proptest = "1.4.0"
