//! Fine-grained error codes for the Kademlia record store.
//! Replaces the single overloaded `kad::store::Error::ValueTooLarge`
//! previously returned for 19+ completely different rejection reasons.

use kinetic_core::error::Severity;
use thiserror::Error;

/// Represents an error returned by the kinetic network storage or event loop layer.
#[derive(Error, Debug, Clone)]
pub enum KineticStoreError {
    /// Payload size limit exceeded.
    #[error("payload exceeds maximum size limit")]
    PayloadTooLarge,
    /// The VDF proof is too old.
    #[error("VDF proof has expired ({age} rounds old)")]
    VdfExpired {
        /// The age in rounds.
        age: u64,
    },
    /// VDF proof is invalid.
    #[error("VDF proof is invalid")]
    InvalidVdf,
    /// Error generated by the VDF engine.
    #[error("VDF engine returned an error: {0}")]
    VdfEngineError(String),
    /// The Ed25519 signature verification failed.
    #[error("signature verification failed")]
    InvalidSignature,
    /// Public key bytes are not valid.
    #[error("public key bytes are malformed")]
    InvalidPublicKey,
    /// Signature bytes are malformed.
    #[error("signature bytes are malformed")]
    MalformedSignature,

    /// Lost the PoW XOR tie-break against an existing record.
    #[error("lost the XOR tie-break against an existing record")]
    TieBroken,
    /// Insufficient iterations to steal this domain name.
    #[error("insufficient VDF iterations to steal this name")]
    InsufficientIterations,
    /// No existing reveal was found for the requested name.
    #[error("no existing reveal found for this name")]
    RevealNotFound,
    /// KID document signature failed verification.
    #[error("KID document signature is invalid")]
    InvalidKidSignature,
    /// The signature on the manifest is invalid.
    #[error("manifest signature is invalid")]
    InvalidManifestSignature,
    /// Record payload didn't match any known prefix.
    #[error("unknown record type prefix")]
    UnknownRecordType,
    /// Drand hex randomness could not be decoded.
    #[error("drand_randomness field contains invalid hex")]
    InvalidDrandHex,
    /// Finding 8: heartbeat pulse was not strictly greater than the stored value.
    #[error("stale heartbeat: received pulse is not newer than existing record")]
    StaleHeartbeat,
    /// Finding 13: HostRoutingRecord failed signature verification or timestamp check.
    #[error("HostRoutingRecord signature verification failed or record is stale")]
    InvalidHostRouteSignature,
    /// The node is rate-limiting reveal ingestion
    #[error("rate limit exceeded for reveal submission")]
    RateLimited,
    /// Reveal commitment is too recent
    #[error("reveal commitment is too recent")]
    StaleReveal,
    /// Missing prior commitment in DHT
    #[error("no prior commitment found in DHT")]
    MissingCommitment,
    /// Insufficient points to spend on reveal
    #[error("insufficient points to spend on reveal")]
    InsufficientPoints,
}

impl KineticStoreError {
    /// Returns the severity level of this error.
    pub fn severity(&self) -> Severity {
        match self {
            Self::TieBroken
            | Self::InsufficientIterations

            | Self::VdfExpired { .. }
            | Self::RevealNotFound => Severity::Info,
            Self::PayloadTooLarge | Self::UnknownRecordType | Self::RateLimited => Severity::Warning,
            Self::InvalidVdf
            | Self::InvalidSignature
            | Self::InvalidPublicKey
            | Self::MalformedSignature
            | Self::VdfEngineError(_)
            | Self::InvalidKidSignature
            | Self::InvalidManifestSignature
            | Self::InvalidDrandHex
            | Self::StaleHeartbeat
            | Self::InvalidHostRouteSignature
            | Self::StaleReveal
            | Self::MissingCommitment
            | Self::InsufficientPoints => Severity::Error,
        }
    }

    /// Logs the error utilizing its severity level with contextual fields
    pub fn log_warning(&self, error_code: &str, name: &str, extra_context: &str) {
        let severity = self.severity();
        match severity {
            Severity::Info => tracing::info!(
                error_code = error_code,
                name = name,
                severity = ?severity,
                "{} {}", extra_context, self
            ),
            Severity::Warning => tracing::warn!(
                error_code = error_code,
                name = name,
                severity = ?severity,
                "{} {}", extra_context, self
            ),
            _ => tracing::error!(
                error_code = error_code,
                name = name,
                severity = ?severity,
                "{} {}", extra_context, self
            ),
        }
    }
}

// Map to the libp2p expected error type.
// The specific KineticStoreError is logged before this conversion is made.
impl From<KineticStoreError> for libp2p::kad::store::Error {
    fn from(_e: KineticStoreError) -> Self {
        libp2p::kad::store::Error::ValueTooLarge
    }
}
