//! Fine-grained error codes for the Kademlia record store.
//! Replaces the single overloaded `kad::store::Error::ValueTooLarge`
//! previously returned for 19+ completely different rejection reasons.

use kinetic_core::error::Severity;
use thiserror::Error;

/// Represents an error returned by the kinetic network storage or event loop layer.
#[derive(Error, Debug, Clone)]
pub enum KineticStoreError {
    /// Payload size limit exceeded.
    #[error("payload exceeds maximum size limit")]
    PayloadTooLarge,
    /// The VDF proof is too old.
    #[error("VDF proof has expired ({age} rounds old)")]
    VdfExpired {
        /// The age in rounds.
        age: u64,
    },
    /// VDF proof is invalid.
    #[error("VDF proof is invalid")]
    InvalidVdf,
    /// Error generated by the VDF engine.
    #[error("VDF engine returned an error: {0}")]
    VdfEngineError(String),
    /// The Ed25519 signature verification failed.
    #[error("signature verification failed")]
    InvalidSignature,
    /// Public key bytes are not valid.
    #[error("public key bytes are malformed")]
    InvalidPublicKey,
    /// Signature bytes are malformed.
    #[error("signature bytes are malformed")]
    MalformedSignature,

    /// Lost the PoW XOR tie-break against an existing record.
    #[error("lost the XOR tie-break against an existing record")]
    TieBroken,
    /// Insufficient iterations to steal this domain name.
    #[error("insufficient VDF iterations to steal this name")]
    InsufficientIterations,
    /// No existing reveal was found for the requested name.
    #[error("no existing reveal found for this name")]
    RevealNotFound,
    /// KID document signature failed verification.
    #[error("KID document signature is invalid")]
    InvalidKidSignature,
    /// The signature on the manifest is invalid.
    #[error("manifest signature is invalid")]
    InvalidManifestSignature,
    /// Record payload didn't match any known prefix.
    #[error("unknown record type prefix")]
    UnknownRecordType,
    /// Drand hex randomness could not be decoded.
    #[error("drand_signature field contains invalid hex")]
    InvalidDrandHex,
    /// Finding 8: heartbeat pulse was not strictly greater than the stored value.
    #[error("stale heartbeat: received pulse is not newer than existing record")]
    StaleHeartbeat,
    /// The network has been emergency paused by the Root Key.
    #[error("network registration and renewals are currently halted")]
    NetworkHalted,
    /// Finding 13: HostRoutingRecord failed signature verification or timestamp check.
    #[error("HostRoutingRecord signature verification failed or record is stale")]
    InvalidHostRouteSignature,
    /// The node is rate-limiting reveal ingestion
    #[error("rate limit exceeded for reveal submission")]
    RateLimited,
    /// Reveal commitment is too recent
    #[error("reveal commitment is too recent")]
    StaleReveal,
    /// Missing prior commitment in DHT
    #[error("no prior commitment found in DHT")]
    MissingCommitment,
    /// Invalid apex domain name
    #[error("the provided name is not a valid kinetic apex domain")]
    InvalidName,
}

impl KineticStoreError {
    /// Stable protocol error code.
    pub fn code(&self) -> &'static str {
        match self {
            Self::PayloadTooLarge => "KIN-NET-001",
            Self::VdfExpired { .. } => "KIN-NET-002",
            Self::InvalidVdf => "KIN-NET-003",
            Self::VdfEngineError(_) => "KIN-NET-004",
            Self::InvalidSignature => "KIN-NET-005",
            Self::InvalidPublicKey => "KIN-NET-006",
            Self::MalformedSignature => "KIN-NET-007",
            Self::TieBroken => "KIN-NET-008",
            Self::InsufficientIterations => "KIN-NET-009",
            Self::RevealNotFound => "KIN-NET-010",
            Self::InvalidKidSignature => "KIN-NET-011",
            Self::InvalidManifestSignature => "KIN-NET-012",
            Self::UnknownRecordType => "KIN-NET-013",
            Self::InvalidDrandHex => "KIN-NET-014",
            Self::StaleHeartbeat => "KIN-NET-015",
            Self::InvalidHostRouteSignature => "KIN-NET-016",
            Self::RateLimited => "KIN-NET-017",
            Self::StaleReveal => "KIN-NET-018",
            Self::MissingCommitment => "KIN-NET-019",
            Self::InvalidName => "KIN-NET-020",
            Self::NetworkHalted => "KIN-NET-021",
        }
    }

    /// RFC 7807 type URI for this error.
    pub fn error_type_uri(&self) -> String {
        format!("https://kinetic.network/errors/{}", self.code())
    }

    /// Returns whether this error is transient and retryable.
    pub fn is_retryable(&self) -> bool {
        matches!(self, Self::RateLimited | Self::VdfEngineError(_))
    }

    /// Human-friendly explanation of the error.
    pub fn user_message(&self) -> String {
        match self {
            Self::PayloadTooLarge => "Record payload exceeds maximum allowed size".to_string(),
            Self::VdfExpired { age } => format!("VDF proof is expired ({} rounds old)", age),
            Self::InvalidVdf => "VDF proof verification failed".to_string(),
            Self::VdfEngineError(err) => format!("VDF engine error: {}", err),
            Self::InvalidSignature => "Signature verification failed".to_string(),
            Self::InvalidPublicKey => "Public key format is invalid".to_string(),
            Self::MalformedSignature => "Signature format is invalid".to_string(),
            Self::TieBroken => "Record lost XOR tie-break against existing DHT entry".to_string(),
            Self::InsufficientIterations => {
                "Insufficient VDF iterations to override existing record".to_string()
            }
            Self::RevealNotFound => "No reveal record found for domain".to_string(),
            Self::InvalidKidSignature => "KID document signature verification failed".to_string(),
            Self::InvalidManifestSignature => "Manifest signature verification failed".to_string(),
            Self::UnknownRecordType => "Record payload prefix is unrecognized".to_string(),
            Self::InvalidDrandHex => "Drand randomness hex string is invalid".to_string(),
            Self::StaleHeartbeat => "Heartbeat pulse is not newer than stored record".to_string(),
            Self::InvalidHostRouteSignature => {
                "Host routing record signature verification failed".to_string()
            }
            Self::RateLimited => "Rate limit exceeded for submission".to_string(),
            Self::StaleReveal => "Reveal commitment is too recent".to_string(),
            Self::MissingCommitment => {
                "No prior commitment found in DHT for this reveal".to_string()
            }
            Self::InvalidName => "Name is not a valid Kinetic apex domain".to_string(),
            Self::NetworkHalted => "Network Registration Halted".to_string(),
        }
    }

    /// Returns the severity level of this error.
    pub fn severity(&self) -> Severity {
        match self {
            Self::TieBroken
            | Self::InsufficientIterations
            | Self::VdfExpired { .. }
            | Self::RevealNotFound => Severity::Info,
            Self::PayloadTooLarge | Self::UnknownRecordType | Self::RateLimited => {
                Severity::Warning
            }
            Self::InvalidVdf
            | Self::InvalidSignature
            | Self::InvalidPublicKey
            | Self::MalformedSignature
            | Self::VdfEngineError(_)
            | Self::InvalidKidSignature
            | Self::InvalidManifestSignature
            | Self::InvalidDrandHex
            | Self::StaleHeartbeat
            | Self::InvalidHostRouteSignature
            | Self::StaleReveal
            | Self::MissingCommitment
            | Self::InvalidName
            | Self::NetworkHalted => Severity::Error,
        }
    }

    /// Logs the error utilizing its severity level with contextual fields
    pub fn log_warning(&self, error_code: &str, name: &str, extra_context: &str) {
        let severity = self.severity();
        match severity {
            Severity::Info => tracing::info!(
                error_code = error_code,
                name = name,
                severity = ?severity,
                "{} {}", extra_context, self
            ),
            Severity::Warning => tracing::warn!(
                error_code = error_code,
                name = name,
                severity = ?severity,
                "{} {}", extra_context, self
            ),
            _ => tracing::error!(
                error_code = error_code,
                name = name,
                severity = ?severity,
                "{} {}", extra_context, self
            ),
        }
    }
}

// Map to the libp2p expected error type.
// The specific KineticStoreError is logged before this conversion is made.
impl From<KineticStoreError> for libp2p::kad::store::Error {
    fn from(_e: KineticStoreError) -> Self {
        libp2p::kad::store::Error::ValueTooLarge
    }
}
