//! Fine-grained error codes for the Kademlia record store.
//! Replaces the single overloaded `kad::store::Error::ValueTooLarge`
//! previously returned for 19+ completely different rejection reasons.

use kinetic_core::error::Severity;
use thiserror::Error;

/// Represents an error returned by the kinetic network storage or event loop layer.
#[derive(Error, Debug, Clone)]
pub enum KineticStoreError {
    /// Payload size limit exceeded.
    #[error("payload exceeds maximum size limit")]
    PayloadTooLarge,
    /// The VDF proof is too old.
    #[error("VDF proof has expired ({age} rounds old)")]
    VdfExpired {
        /// The age in rounds.
        age: u64,
    },
    /// VDF proof is invalid.
    #[error("VDF proof is invalid")]
    InvalidVdf,
    /// Error generated by the VDF engine.
    #[error("VDF engine returned an error: {0}")]
    VdfEngineError(String),
    /// The Ed25519 signature verification failed.
    #[error("signature verification failed")]
    InvalidSignature,
    /// Public key bytes are not valid.
    #[error("public key bytes are malformed")]
    InvalidPublicKey,
    /// Signature bytes are malformed.
    #[error("signature bytes are malformed")]
    MalformedSignature,
    /// Lost the PoW XOR tie-break against an existing record.
    #[error("lost the XOR tie-break against an existing record")]
    TieBroken,
    /// Insufficient iterations to steal this name.
    #[error("insufficient VDF iterations to steal this name")]
    InsufficientIterations,
    /// Internal Kademlia store failure
    #[error("internal Kademlia DHT store failed to save the record")]
    InternalStoreError,
    /// KID document signature failed verification.
    #[error("KID document signature is invalid")]
    InvalidKidSignature,
    /// The signature on the manifest is invalid.
    #[error("manifest signature is invalid")]
    InvalidManifestSignature,
    /// Record payload didn't match any known prefix.
    #[error("unknown record type prefix")]
    UnknownRecordType,
    /// Drand hex randomness could not be decoded.
    #[error("drand_signature field contains invalid hex")]
    InvalidDrandHex,
    /// Finding 8: heartbeat kyn was not strictly greater than the stored value.
    #[error("stale heartbeat: received kyn is not newer than existing record")]
    StaleHeartbeat,
    /// Finding 13: HostRoutingRecord failed signature verification or timestamp check.
    #[error("HostRoutingRecord signature verification failed or record is stale")]
    InvalidHostRouteSignature,
    /// The node is rate-limiting reveal ingestion
    #[error("rate limit exceeded for reveal submission")]
    RateLimited,
    /// Reveal commitment is too recent
    #[error("reveal commitment is too recent")]
    StaleReveal,
    /// JSON is valid but does not match the strict Kinetic schema
    #[error("payload violates the expected record schema")]
    SchemaValidationError,
    /// Invalid apex name
    #[error("the provided name is not a valid kinetic apex name")]
    InvalidName,
    /// The network has been emergency paused by the Root Key.
    #[error("network registration and renewals are currently halted")]
    NetworkHalted,
    /// The delegated manifest does not grant the required capability.
    #[error("delegated capability missing from authorized manifest")]
    DelegatedCapabilityMissing,
    /// The delegated authorization proof is structurally invalid or fails signature check.
    #[error("delegated authorization proof is invalid")]
    DelegatedAuthorizationInvalid,
    /// Drand BLS signature failed math verification
    #[error("drand signature failed BLS verification")]
    InvalidDrandSignature,
    /// Raw bytes could not be parsed as JSON
    #[error("payload contains malformed or invalid JSON")]
    MalformedJson,
    /// KID document failed internal validation
    #[error("kid document failed validation")]
    InvalidKidDocument,
    /// Initial DID binding failed
    #[error("genesis binding failed")]
    GenesisBindingFailed,
    /// Unauthorized update
    #[error("update is not authorized by prior key")]
    UnauthorizedUpdate,
    /// Manifest version rollback
    #[error("manifest version rollback detected")]
    ManifestVersionRollback,
    /// Manifest local verification failed
    #[error("manifest local verification failed")]
    ManifestVerificationFailed,
    /// Heartbeat timestamp is in the future
    #[error("heartbeat timestamp is too far in the future")]
    FutureHeartbeat,
    /// Name type is immutable
    #[error("Prime and Infra names are immutable and cannot be stolen")]
    ImmutableName,
    
    // ==========================================
    // KIN-QRY Error Codes
    // ==========================================
    
    /// No existing reveal was found for the requested name.
    #[error("no existing reveal found for this name")]
    RevealNotFound,
    /// Missing prior commitment in DHT
    #[error("no prior commitment found in DHT")]
    MissingCommitment {
        /// The derived Kademlia DHT key of the missing commitment.
        commit_key: Vec<u8>,
    },
    /// Name not found locally
    #[error("name not found locally")]
    NameNotFound,
    /// KID document missing
    #[error("KID document is missing from the authorization payload")]
    MissingKidDocument,
}

impl KineticStoreError {
    /// Stable protocol error code.
    pub fn code(&self) -> &'static str {
        match self {
            Self::PayloadTooLarge => "KIN-NET-001",
            Self::VdfExpired { .. } => "KIN-NET-002",
            Self::InvalidVdf => "KIN-NET-003",
            Self::VdfEngineError(_) => "KIN-NET-004",
            Self::InvalidSignature => "KIN-NET-005",
            Self::InvalidPublicKey => "KIN-NET-006",
            Self::MalformedSignature => "KIN-NET-007",
            Self::TieBroken => "KIN-NET-008",
            Self::InsufficientIterations => "KIN-NET-009",
            Self::InternalStoreError => "KIN-NET-010",
            Self::InvalidKidSignature => "KIN-NET-011",
            Self::InvalidManifestSignature => "KIN-NET-012",
            Self::UnknownRecordType => "KIN-NET-013",
            Self::InvalidDrandHex => "KIN-NET-014",
            Self::StaleHeartbeat => "KIN-NET-015",
            Self::InvalidHostRouteSignature => "KIN-NET-016",
            Self::RateLimited => "KIN-NET-017",
            Self::StaleReveal => "KIN-NET-018",
            Self::SchemaValidationError => "KIN-NET-019",
            Self::InvalidName => "KIN-NET-020",
            Self::NetworkHalted => "KIN-NET-021",
            Self::DelegatedCapabilityMissing => "KIN-NET-022",
            Self::DelegatedAuthorizationInvalid => "KIN-NET-023",
            Self::InvalidDrandSignature => "KIN-NET-024",
            Self::MalformedJson => "KIN-NET-025",
            Self::InvalidKidDocument => "KIN-NET-026",
            Self::GenesisBindingFailed => "KIN-NET-027",
            Self::UnauthorizedUpdate => "KIN-NET-028",
            Self::ManifestVersionRollback => "KIN-NET-029",
            Self::ManifestVerificationFailed => "KIN-NET-030",
            Self::FutureHeartbeat => "KIN-NET-031",
            Self::ImmutableName => "KIN-NET-032",

            Self::RevealNotFound => "KIN-QRY-007",
            Self::MissingCommitment { .. } => "KIN-QRY-008",
            Self::NameNotFound => "KIN-QRY-009",
            Self::MissingKidDocument => "KIN-QRY-010",
        }
    }

    /// RFC 7807 type URI for this error.
    pub fn error_type_uri(&self) -> String {
        format!("https://kinetic.network/errors/{}", self.code())
    }

    /// Returns whether this error is transient and retryable.
    pub fn is_retryable(&self) -> bool {
        matches!(self, Self::RateLimited | Self::VdfEngineError(_))
    }

    /// Human-friendly explanation of the error.
    pub fn user_message(&self) -> String {
        match self {
            Self::PayloadTooLarge => "Record payload exceeds maximum allowed size".to_string(),
            Self::VdfExpired { age } => format!("VDF proof is expired ({} rounds old)", age),
            Self::InvalidVdf => "VDF proof verification failed".to_string(),
            Self::VdfEngineError(err) => format!("VDF engine error: {}", err),
            Self::InvalidSignature => "Signature verification failed".to_string(),
            Self::InvalidPublicKey => "Public key format is invalid".to_string(),
            Self::MalformedSignature => "Signature format is invalid".to_string(),
            Self::TieBroken => "Record lost XOR tie-break against existing DHT entry".to_string(),
            Self::InsufficientIterations => {
                "Insufficient VDF iterations to override existing record".to_string()
            }
            Self::InternalStoreError => {
                "Internal DHT memory store rejected the put operation".to_string()
            }
            Self::InvalidKidSignature => "KID document signature verification failed".to_string(),
            Self::InvalidManifestSignature => "Manifest signature verification failed".to_string(),
            Self::UnknownRecordType => "Record payload prefix is unrecognized".to_string(),
            Self::InvalidDrandHex => "Drand randomness hex string is invalid".to_string(),
            Self::StaleHeartbeat => "Heartbeat kyn is not newer than stored record".to_string(),
            Self::InvalidHostRouteSignature => {
                "Host routing record signature verification failed".to_string()
            }
            Self::RateLimited => "Rate limit exceeded for submission".to_string(),
            Self::StaleReveal => "Reveal commitment is too recent".to_string(),
            Self::SchemaValidationError => "Parsed JSON failed strict type validation".to_string(),
            Self::InvalidName => "Name is not a valid Kinetic apex name".to_string(),
            Self::NetworkHalted => "Network Registration Halted".to_string(),
            Self::DelegatedCapabilityMissing => {
                "The delegated manifest does not grant the required capability for this action."
                    .to_string()
            }
            Self::DelegatedAuthorizationInvalid => {
                "The delegated authorization proof could not be verified against the master key."
                    .to_string()
            }
            Self::InvalidDrandSignature => "Drand signature math verification failed".to_string(),
            Self::MalformedJson => "Failed to parse raw bytes as JSON".to_string(),
            Self::InvalidKidDocument => "KID document failed self-verification".to_string(),
            Self::GenesisBindingFailed => "KID genesis binding failed on first publish".to_string(),
            Self::UnauthorizedUpdate => {
                "KID update is not authorized by existing active record".to_string()
            }
            Self::ManifestVersionRollback => {
                "Manifest version must be strictly increasing".to_string()
            }
            Self::ManifestVerificationFailed => "Manifest failed local verification".to_string(),
            Self::FutureHeartbeat => "Heartbeat timestamp is from the future".to_string(),
            Self::ImmutableName => {
                "This name type is immortal and cannot be transferred via PoW".to_string()
            }

            Self::RevealNotFound => "No reveal record found for name".to_string(),
            Self::MissingCommitment { .. } => {
                "No prior commitment found in DHT for this reveal".to_string()
            }
            Self::NameNotFound => "Active record missing for this name".to_string(),
            Self::MissingKidDocument => {
                "Authorization payload is missing the required KID document".to_string()
            }
        }
    }

    /// Returns the severity level of this error.
    pub fn severity(&self) -> Severity {
        match self {
            Self::TieBroken
            | Self::InsufficientIterations
            | Self::VdfExpired { .. }
            | Self::RevealNotFound
            | Self::NameNotFound => Severity::Info,
            Self::PayloadTooLarge | Self::UnknownRecordType | Self::RateLimited => {
                Severity::Warning
            }
            Self::InvalidVdf
            | Self::InvalidSignature
            | Self::InvalidPublicKey
            | Self::MalformedSignature
            | Self::VdfEngineError(_)
            | Self::InvalidKidSignature
            | Self::InvalidManifestSignature
            | Self::InvalidDrandHex
            | Self::StaleHeartbeat
            | Self::InvalidHostRouteSignature
            | Self::StaleReveal
            | Self::MissingCommitment { .. }
            | Self::InvalidName
            | Self::NetworkHalted
            | Self::DelegatedCapabilityMissing
            | Self::DelegatedAuthorizationInvalid
            | Self::InvalidDrandSignature
            | Self::InvalidKidDocument
            | Self::GenesisBindingFailed
            | Self::UnauthorizedUpdate
            | Self::ManifestVersionRollback
            | Self::ManifestVerificationFailed
            | Self::FutureHeartbeat
            | Self::ImmutableName
            | Self::MissingKidDocument
            | Self::MalformedJson
            | Self::SchemaValidationError
            | Self::InternalStoreError => Severity::Error,
        }
    }

    /// Logs the error utilizing its severity level with contextual fields
    pub fn log_warning(&self, name: &str, extra_context: &str) {
        let severity = self.severity();
        let error_code = self.code();
        match severity {
            Severity::Info => tracing::info!(
                error_code = error_code,
                name = name,
                severity = ?severity,
                "{} {}", extra_context, self
            ),
            Severity::Warning => tracing::warn!(
                error_code = error_code,
                name = name,
                severity = ?severity,
                "{} {}", extra_context, self
            ),
            _ => tracing::error!(
                error_code = error_code,
                name = name,
                severity = ?severity,
                "{} {}", extra_context, self
            ),
        }
    }
}

// Map to the libp2p expected error type.
// The specific KineticStoreError is logged before this conversion is made.
impl From<KineticStoreError> for libp2p::kad::store::Error {
    fn from(_e: KineticStoreError) -> Self {
        libp2p::kad::store::Error::ValueTooLarge
    }
}
