[package]
name = "kinetic-keygen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bip39 = "2.2.2"
clap = { version = "4.5.4", features = ["derive"] }
dialoguer = "0.12.0"
getrandom = "0.4.3"
hex = "0.4.3"
kinetic-core = { version = "0.1.0", path = "../kinetic-core" }
ml-dsa = "0.1.1"
pbkdf2 = "0.13.0"
sha2 = "0.11.0"
base64 = "0.22.0"
chrono = "0.4.38"
aes-gcm = "0.10.3"

