[workspace]
members = [
    "kinetic-core",
    "kinetic-network",
    "kinetic-storage",
    "kinetic-nrs",
    "kinetic-daemon", "kinetic-cli", "kinetic-test", "kinetic-kid", "kinetic-node",
    "kinetic-host", "kinetic-wasm", "kinetic-forge", "kinetic-pac",
    "kinetic-verify", "kinetic-types"
, "kinetic-primitives", "kinetic-local", "kinetic-rpc"]
exclude = [
    "kinetic-core/fuzz",
    "kinetic-daemon/fuzz",
    "axum_test",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Saif Mukhtar <saifmukhtar20@gmail.com>"]
repository = "https://github.com/saifmukhtar/kinetic"
homepage = "https://github.com/saifmukhtar/kinetic"

[workspace.dependencies]
# Common Workspace Dependencies (Ensures all crates use the same versions)
anyhow = "1.0.86"
thiserror = "1.0.61"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tokio = { version = "1.38.0", features = ["full"] }

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
