//! Verifiable Delay Function (VDF) commitments, reveal payloads, and proof models.
//!
//! This module defines the cryptographic wire-format structures for the two-phase registration protocol:
//! 1. **Commit Phase**: A hash commitment ([`Commitment`]) is submitted to the network.
//! 2. **Reveal Phase**: The computational VDF proof ([`VdfProof`]) and reveal payload ([`Reveal`]) are published with an ML-DSA-65 post-quantum signature.

use super::names::is_valid_apex_name;
use serde::{Deserialize, Serialize};

/// Resquaring epoch interval in drand rounds (~6 months / 182.5 days at 3 seconds per round).
pub const RESQUARING_EPOCH_ROUNDS: u64 = 5_256_000;
/// Maximum allowed byte size for a domain reveal payload (64 KB).
pub const MAX_PAYLOAD_SIZE: usize = 65_536;

/// Cryptographic SHA-256 hash commitment to a registration request.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Commitment {
    /// 32-byte SHA-256 commitment hash.
    pub hash: [u8; 32],
}

/// Raw proof bytes generated by the chiavdf Verifiable Delay Function engine.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VdfProof {
    /// Raw VDF evaluation proof bytes.
    pub proof_bytes: Vec<u8>,
}

/// Initial commitment submission request payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommitRequest {
    /// Target `.kin` domain name.
    pub name: String,
    /// Cryptographic commitment.
    pub commitment: Commitment,
}

fn default_protocol_version() -> u8 {
    1
}

/// Previous VDF proof link in a chained domain renewal proof sequence.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PreviousProof {
    /// 32-byte salt used in the previous proof generation.
    pub salt: [u8; 32],
    /// Drand round number associated with the previous proof.
    pub drand_pulse: u64,
    /// Hex-encoded drand randomness string.
    pub drand_randomness: String,
    /// Iteration count of the previous proof.
    pub iterations: u64,
    /// Embedded VDF proof bytes.
    pub vdf_proof: VdfProof,
    /// Signature of the previous proof.
    pub signature: Vec<u8>,
}

impl PreviousProof {
    /// Serializes this previous proof into canonical bytes for chained renewal proof inclusion.
    ///
    /// The byte layout is:
    /// `{NETWORK_ID}-vdf-prev-v1` + `salt[32]` + `u64_be(drand_pulse)` +
    /// `u32_be(drand_randomness.len())` + `drand_randomness_bytes` +
    /// `u64_be(iterations)` + `u32_be(vdf_proof.len())` + `vdf_proof_bytes` +
    /// `u32_be(signature.len())` + `signature_bytes`
    ///
    /// # Returns
    ///
    /// A `Vec<u8>` containing the fully serialized previous proof for canonical signing.
    pub fn proof_bytes(&self) -> Vec<u8> {
        let prefix = concat!(env!("KINETIC_NETWORK_ID"), "-vdf-prev-v1").as_bytes();
        let capacity = prefix.len()
            + 32 // salt
            + 8 // drand_pulse
            + 4 + self.drand_randomness.len()
            + 8 // iterations
            + 4 + self.vdf_proof.proof_bytes.len()
            + 4 + self.signature.len();

        let mut bytes = Vec::with_capacity(capacity);
        bytes.extend_from_slice(prefix);
        bytes.extend_from_slice(&self.salt);
        bytes.extend_from_slice(&self.drand_pulse.to_be_bytes());

        bytes.extend_from_slice(&(self.drand_randomness.len() as u32).to_be_bytes());
        bytes.extend_from_slice(self.drand_randomness.as_bytes());

        bytes.extend_from_slice(&self.iterations.to_be_bytes());

        bytes.extend_from_slice(&(self.vdf_proof.proof_bytes.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.vdf_proof.proof_bytes);

        bytes.extend_from_slice(&(self.signature.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.signature);

        bytes
    }
}

/// Revealed domain registration payload submitted to the network during Phase 2.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Reveal {
    /// Protocol version indicator (default: `1`).
    #[serde(default = "default_protocol_version")]
    pub protocol_version: u8,
    /// Registered `.kin` domain name.
    pub name: String,
    /// Arbitrary domain metadata or DNS zone record payload bytes.
    pub payload: Vec<u8>,
    /// 32-byte salt value for commitment blinding.
    pub salt: [u8; 32],
    /// Associated drand randomness round number.
    pub drand_pulse: u64,
    /// Hex-encoded drand randomness seed string.
    pub drand_randomness: String,
    /// Number of VDF iterations completed.
    pub iterations: u64,
    /// Evaluated VDF proof.
    pub vdf_proof: VdfProof,
    /// ML-DSA-65 public key of the domain owner.
    pub pubkey: Vec<u8>,
    /// ML-DSA-65 post-quantum signature over `signable_bytes`.
    pub signature: Vec<u8>,
    /// Optional chained proof for domain renewal operations.
    pub previous_proof: Option<PreviousProof>,
    /// Optional public key of the miner that computed the VDF proof.
    pub miner_pubkey: Option<Vec<u8>>,
}

impl Reveal {
    /// Validates the reveal payload structure against protocol rules.
    ///
    /// # Errors
    ///
    /// - Returns [`crate::error::KineticError::Internal`] if `protocol_version != 1`.
    /// - Returns [`crate::error::KineticError::InvalidName`] (wrapping [`crate::error::NamesError`]) if the domain fails apex validation rules.
    /// - Returns [`crate::error::KineticError::Internal`] if the payload size exceeds `MAX_PAYLOAD_SIZE`.
    pub fn validate(&self) -> Result<(), crate::error::KineticError> {
        if self.protocol_version != 1 {
            return Err(crate::error::KineticError::Internal(format!(
                "Invalid protocol version {}. Only protocol version 1 is supported.",
                self.protocol_version
            )));
        }

        is_valid_apex_name(&self.name)?;

        if self.payload.len() > MAX_PAYLOAD_SIZE {
            return Err(crate::error::KineticError::Internal(format!(
                "Payload size {} exceeds MAX_PAYLOAD_SIZE {}",
                self.payload.len(),
                MAX_PAYLOAD_SIZE
            )));
        }
        Ok(())
    }

    /// Verifies the ML-DSA-65 post-quantum signature over [`signable_bytes`](Reveal::signable_bytes).
    ///
    /// # Returns
    ///
    /// `true` if the signature is cryptographically valid for the embedded public key; `false` if key parsing, signature decoding, or verification fails.
    pub fn verify_signature(&self) -> bool {
        use ml_dsa::signature::Verifier;
        use ml_dsa::KeyInit;
        let signable = self.signable_bytes();
        if let Ok(pubkey) =
            ml_dsa::VerifyingKey::<ml_dsa::MlDsa65>::new_from_slice(self.pubkey.as_slice())
        {
            if let Ok(sig) =
                ml_dsa::Signature::<ml_dsa::MlDsa65>::try_from(self.signature.as_slice())
            {
                return pubkey.verify(&signable, &sig).is_ok();
            }
        }
        false
    }

    /// Serializes the reveal payload into a canonical byte string for ML-DSA-65 signature.
    ///
    /// All variable-length fields are length-prefixed with `u32_be` to prevent
    /// canonicalization ambiguity attacks. The byte layout is:
    /// `{NETWORK_ID}-vdf-reveal-v1` + `u8(protocol_version)` +
    /// `u32_be(name.len())` + `name_bytes` +
    /// `u32_be(payload.len())` + `payload_bytes` +
    /// `salt[32]` + `u64_be(drand_pulse)` +
    /// `u32_be(drand_randomness.len())` + `drand_randomness_bytes` +
    /// `u64_be(iterations)` +
    /// `u32_be(vdf_proof.len())` + `vdf_proof_bytes` +
    /// `u32_be(pubkey.len())` + `pubkey_bytes` +
    /// `u8(has_previous_proof)` + optional previous_proof_bytes +
    /// `u8(has_miner_pubkey)` + optional miner_pubkey_bytes
    ///
    /// # Returns
    ///
    /// A `Vec<u8>` containing the fully serialized signable payload.
    pub fn signable_bytes(&self) -> Vec<u8> {
        let prefix = concat!(env!("KINETIC_NETWORK_ID"), "-vdf-reveal-v1").as_bytes();
        let prev_proof_bytes = self
            .previous_proof
            .as_ref()
            .map(|p| p.proof_bytes())
            .unwrap_or_default();

        // OPTIMIZATION: Calculate exact capacity to prevent multiple reallocations
        let mut capacity = prefix.len()
            + 1 // protocol_version
            + 4 + self.name.len()
            + 4 + self.payload.len()
            + 32 // salt
            + 8 // drand_pulse
            + 4 + self.drand_randomness.len()
            + 8 // iterations
            + 4 + self.vdf_proof.proof_bytes.len()
            + 4 + self.pubkey.len()
            + 1; // previous_proof option flag

        if self.previous_proof.is_some() {
            capacity += 4 + prev_proof_bytes.len();
        }

        capacity += 1; // miner_pubkey option flag
        if let Some(miner_pk) = &self.miner_pubkey {
            capacity += 4 + miner_pk.len();
        }

        let mut bytes = Vec::with_capacity(capacity);
        bytes.extend_from_slice(prefix);
        bytes.push(self.protocol_version);

        // SECURITY: Length-prefix all variable-length fields (u32) to prevent canonicalization ambiguity attacks
        bytes.extend_from_slice(&(self.name.len() as u32).to_be_bytes());
        bytes.extend_from_slice(self.name.as_bytes());

        bytes.extend_from_slice(&(self.payload.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.payload);

        bytes.extend_from_slice(&self.salt);
        bytes.extend_from_slice(&self.drand_pulse.to_be_bytes());

        bytes.extend_from_slice(&(self.drand_randomness.len() as u32).to_be_bytes());
        bytes.extend_from_slice(self.drand_randomness.as_bytes());

        bytes.extend_from_slice(&self.iterations.to_be_bytes());

        bytes.extend_from_slice(&(self.vdf_proof.proof_bytes.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.vdf_proof.proof_bytes);

        bytes.extend_from_slice(&(self.pubkey.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.pubkey);

        if self.previous_proof.is_some() {
            bytes.push(1);
            bytes.extend_from_slice(&(prev_proof_bytes.len() as u32).to_be_bytes());
            bytes.extend_from_slice(&prev_proof_bytes);
        } else {
            bytes.push(0);
        }

        if let Some(miner_pk) = &self.miner_pubkey {
            bytes.push(1);
            bytes.extend_from_slice(&(miner_pk.len() as u32).to_be_bytes());
            bytes.extend_from_slice(miner_pk);
        } else {
            bytes.push(0);
        }

        bytes
    }
}

/// Request parameters for initiating a new VDF computation job.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VdfJobRequest {
    /// 32-byte target SHA-256 challenge commitment hash.
    pub challenge_hash: [u8; 32],
    /// Character length of the domain label being registered.
    pub name_length: u8,
    /// Evaluated Hashcash proof-of-work nonce.
    pub hashcash_nonce: u64,
    /// Associated drand randomness round number.
    pub drand_pulse: u64,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::constants::TLD_SUFFIX;

    #[test]
    fn test_signable_bytes() {
        let reveal = Reveal {
            protocol_version: 1,
            name: format!("myname{}", TLD_SUFFIX),
            payload: vec![1, 2, 3],
            salt: [0u8; 32],
            drand_pulse: 100,
            drand_randomness: "randomness".to_string(),
            iterations: 1000,
            vdf_proof: VdfProof {
                proof_bytes: vec![4, 5, 6],
            },
            pubkey: vec![7, 8, 9],
            signature: vec![],
            previous_proof: None,
            miner_pubkey: None,
        };
        let bytes = reveal.signable_bytes();
        let prefix = concat!(env!("KINETIC_NETWORK_ID"), "-vdf-reveal-v1").as_bytes();
        assert!(bytes.starts_with(prefix));
        assert_eq!(bytes[prefix.len()], 1); // protocol version follows the prefix
        assert!(bytes.len() > 10);
    }
}
