//! Strict semantic wrappers for the Kinetic Network Key Taxonomy.
//!
//! # The Abstraction Boundary
//! The Kinetic Network relies entirely on the ML-DSA-65 post-quantum signature scheme 
//! (represented internally by `KineticKeypair`). Because all keys share the exact same 
//! underlying mathematical properties, relying on raw `KineticKeypair` objects throughout 
//! the workspace invites catastrophic authorization vulnerabilities. 
//! 
//! (e.g., A developer accidentally passing a `DelegatedKey` into a function that 
//! expects an `IdentityKey`, and the compiler silently allowing it).
//!
//! # Newtype Pattern
//! To enforce physical authorization boundaries at compile time, this module wraps the 
//! raw cryptographic primitives into strict semantic domain types defined in `KEY_TAXONOMY.md`.
//! 
//! Every logical key is split into two explicit halves:
//! * `*PrivKey`: The highly sensitive private signing material.
//! * `*PubKey`: The public verifier, which is safe to transmit across the network.
//!
//! # Examples
//! ```rust
//! use kinetic_primitives::kinetic_keypair::{ControllerPrivKey, ControllerPubKey};
//!
//! // 1. Generate a new Controller key
//! let controller = ControllerPrivKey::generate();
//!
//! // 2. Sign a payload
//! let signature = controller.sign(b"rotate_document");
//!
//! // 3. Extract the public key safely for network transmission
//! let pubkey: ControllerPubKey = controller.to_pubkey();
//!
//! // 4. Export the private key to storage (DANGER)
//! let secret_bytes = controller.to_secret_bytes();
//! ```

use crate::keys::KineticKeypair;

/// 1. Identity Key
/// The root of trust, derived directly from the user's master seed phrase.
#[derive(Clone)]
pub struct IdentityPrivKey(pub KineticKeypair);

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct IdentityPubKey(pub Vec<u8>);

/// 2. Controller Key
/// The active "hot" key embedded in a Kinetic Identity Document (KID).
#[derive(Clone)]
pub struct ControllerPrivKey(pub KineticKeypair);

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ControllerPubKey(pub Vec<u8>);

/// 3. Revoke Key
/// The highly secure "dark" key used exclusively to permanently deactivate a KID.
#[derive(Clone)]
pub struct RevokePrivKey(pub KineticKeypair);

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RevokePubKey(pub Vec<u8>);

/// 4. Delegated Key
/// The ephemeral key used by headless seeders to operate on behalf of an identity.
#[derive(Clone)]
pub struct DelegatedPrivKey(pub KineticKeypair);

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DelegatedPubKey(pub Vec<u8>);

/// 5. Sovereign Key
/// The global root key used to authorize network-level state changes.
#[derive(Clone)]
pub struct SovereignPrivKey(pub KineticKeypair);

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SovereignPubKey(pub Vec<u8>);

macro_rules! impl_taxonomy_key {
    ($priv_type:ident, $pub_type:ident) => {
        impl $priv_type {
            pub fn generate() -> Self { Self(KineticKeypair::generate()) }
            pub fn sign(&self, msg: &[u8]) -> Vec<u8> { self.0.sign(msg) }
            pub fn to_pubkey(&self) -> $pub_type { $pub_type(self.0.pubkey_bytes()) }
            pub fn to_secret_bytes(&self) -> Vec<u8> { self.0.to_bytes() }
            pub fn from_seed(seed: &[u8; 32]) -> Self { Self(KineticKeypair::from_seed(seed)) }
            pub fn from_slice(bytes: &[u8]) -> Result<Self, &'static str> {
                KineticKeypair::from_slice(bytes).map(Self)
            }
        }

        impl $pub_type {
            /// Cryptographically verifies that the provided signature was generated by the 
            /// matching private key over the exact provided message.
            pub fn verify(&self, msg: &[u8], signature: &[u8]) -> Result<(), crate::SignatureError> {
                crate::verify_keypair(&self.0, msg, signature)
            }
        }
    };
}

impl_taxonomy_key!(IdentityPrivKey, IdentityPubKey);
impl_taxonomy_key!(ControllerPrivKey, ControllerPubKey);
impl_taxonomy_key!(RevokePrivKey, RevokePubKey);
impl_taxonomy_key!(DelegatedPrivKey, DelegatedPubKey);
impl_taxonomy_key!(SovereignPrivKey, SovereignPubKey);
