[package]
name = "kinetic-kyn"
version = "0.2.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
beacon-verify = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
kinetic-primitives = { path = "../kinetic-primitives" }

[features]
default = ["beacon"]
beacon = ["dep:beacon-verify", "dep:hex"]

[build-dependencies]
serde_json = { workspace = true }
