[package]
name = "kinetic-pac"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "The local Proxy Auto-Config (PAC) HTTP server for the Kinetic Network."
readme = "README.md"

[[bin]]
name = "kinetic-pac"
path = "src/main.rs"

[features]

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap = { workspace = true, features = ["derive"] }
dirs.workspace = true
kinetic-core = { path = "../kinetic-core" }
reqwest = { workspace = true, features = ["blocking"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
service-manager.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["net", "rt", "rt-multi-thread", "macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
