//! CLI commands for submitting, signing, and managing post-quantum Kinetic network action proposals.

use clap::Subcommand;
use kinetic_core::config::KineticConfig;
use kinetic_core::action::SignedActionMessage;
use reqwest::Client;
use std::path::PathBuf;

#[derive(Subcommand)]
pub enum ActionCommands {
    /// Publish a pre-signed action JSON file generated by kinetic-OS
    Publish {
        /// Path to the signed_action.json file
        #[arg(long)]
        file: PathBuf,
    },
    /// View the status of the current active network action proposal
    Status,
    /// List the Prime Names authorized to vote on network actions
    Names,
}

/// Dispatches action-related CLI subcommands.
pub async fn handle_action_command(
    cmd: ActionCommands,
    config: &KineticConfig,
    client: &Client,
) -> anyhow::Result<()> {
    let port = config.daemon.api_port;
    let base_url = format!("http://{}:{}", config.daemon.bind_ip, port);
    
    // Grab admin token
    let token_path = kinetic_local::config::get_api_tokens_dir().join("admin.token");
    let token = std::fs::read_to_string(&token_path).unwrap_or_default();
    let auth_header = format!("Bearer {}", token.trim());

    match cmd {
        ActionCommands::Publish { file } => {
            let msg_str = std::fs::read_to_string(&file).map_err(|e| {
                anyhow::anyhow!("Failed to read action file {}: {}", file.display(), e)
            })?;
            let msg: SignedActionMessage = serde_json::from_str(&msg_str)
                .map_err(|e| anyhow::anyhow!("Failed to parse action JSON: {}", e))?;

            let publish_url = format!("{}/api/v1/micro/action/publish", base_url);
            let pb = indicatif::ProgressBar::new_spinner();
            pb.set_style(indicatif::ProgressStyle::default_spinner().template("{spinner:.cyan} {msg}")?);
            pb.set_message("Publishing action...");
            pb.enable_steady_tick(std::time::Duration::from_millis(100));

            let publish_resp = client
                .post(&publish_url)
                .header("Authorization", &auth_header)
                .json(&msg)
                .send()
                .await?;

            pb.finish_and_clear();

            if publish_resp.status().is_success() {
                println!("✅ Successfully published action to the Kinetic Network!");
            } else {
                let err_text = publish_resp.text().await?;
                anyhow::bail!("Failed to publish action: {}", err_text);
            }
        }
        ActionCommands::Status => {
            let url = format!("{}/api/v1/micro/action/status", base_url);
            let resp = client.get(&url).header("Authorization", &auth_header).send().await?;
            if !resp.status().is_success() {
                anyhow::bail!("Failed to fetch action status: {}", resp.text().await?);
            }
            let json: serde_json::Value = resp.json().await?;
            println!("{}", serde_json::to_string_pretty(&json)?);
        }
        ActionCommands::Names => {
            let url = format!("{}/api/v1/micro/action/names", base_url);
            let resp = client.get(&url).header("Authorization", &auth_header).send().await?;
            if !resp.status().is_success() {
                anyhow::bail!("Failed to fetch action prime names: {}", resp.text().await?);
            }
            let json: serde_json::Value = resp.json().await?;
            println!("{}", serde_json::to_string_pretty(&json)?);
        }
    }

    Ok(())
}
