//! CLI commands for submitting, signing, and managing post-quantum Kinetic network governance proposals.

use clap::Subcommand;
use kinetic_core::config::KineticConfig;
use kinetic_core::action::SignedGovernanceMessage;
use reqwest::Client;
use std::path::PathBuf;

#[derive(Subcommand)]
pub enum ActionCommands {
    /// Broadcast a pre-signed governance JSON file generated by kinetic-OS
    Broadcast {
        /// Path to the signed_action.json file
        #[arg(long)]
        file: PathBuf,
    },
}

/// Reads a pre-signed governance message from a JSON file and broadcasts it to the network via the local daemon.
///
/// # Errors
/// Returns an `anyhow::Error` if:
/// - The specified JSON file cannot be read from disk.
/// - The JSON contents cannot be parsed into a `SignedGovernanceMessage`.
/// - The `admin.token` cannot be found or read from the local API token directory.
/// - The daemon API cannot be reached or returns a non-200 HTTP error status.
pub async fn handle_governance_command(
    cmd: ActionCommands,
    config: &KineticConfig,
    client: &Client,
) -> anyhow::Result<()> {
    let msg: SignedGovernanceMessage = match cmd {
        ActionCommands::Broadcast { file } => {
            let msg_str = std::fs::read_to_string(&file).map_err(|e| {
                anyhow::anyhow!("Failed to read governance file {}: {}", file.display(), e)
            })?;
            serde_json::from_str(&msg_str)
                .map_err(|e| anyhow::anyhow!("Failed to parse governance JSON: {}", e))?
        }
    };

    // Publish to the daemon
    let port = config.daemon.api_port;
    let token =
        std::fs::read_to_string(kinetic_local::config::get_api_tokens_dir().join("admin.token"))?;

    let publish_url = format!(
        "http://{}:{}/api/v1/micro/action/publish",
        config.daemon.bind_ip, port
    );
    let pb = indicatif::ProgressBar::new_spinner();
    pb.set_style(indicatif::ProgressStyle::default_spinner().template("{spinner:.cyan} {msg}")?);
    pb.set_message("Publishing governance action...");
    pb.enable_steady_tick(std::time::Duration::from_millis(100));

    let publish_resp = client
        .post(&publish_url)
        .header("Authorization", format!("Bearer {}", token.trim()))
        .json(&msg)
        .send()
        .await?;

    pb.finish_and_clear();

    if publish_resp.status().is_success() {
        println!("Successfully published governance action to the Kinetic Network!");
    } else {
        let err_text = publish_resp.text().await?;
        println!("Failed to publish governance action: {}", err_text);
    }

    Ok(())
}
