[package]
name = "kinetic-kid"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
description = "Kinetic Identity Document (KID) implementation for the Kinetic Network."
keywords = ["kinetic", "identity", "kid", "crypto"]
categories = ["cryptography", "authentication"]

[features]
simulation = []

[dependencies]
# --- Workspace & Internal Crates ---
kinetic-primitives = { path = "../kinetic-primitives" }

# --- External Crates ---
base64.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_jcs.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
rand_core = { workspace = true, features = ["getrandom"] }
proptest.workspace = true

[build-dependencies]
serde_json.workspace = true
