//! Governance action verification and voting error types (`KIN-ACN-NNN`).
//!
//! [`GovernanceError`] is returned by the active [`GovernanceEngine`](crate::traits::GovernanceEngine)
//! when a [`SignedGovernanceMessage`](crate::governance::types::SignedGovernanceMessage) fails
//! signature verification, threshold checks, or timelock constraints.
//!
//! ## Protocol Context
//!
//! Kinetic governance is pluggable: `network.json` selects one of the engines
//! (`sovereign` or `permissionless`) at compile time. Each engine
//! runs `verify_action()` before any state mutation occurs.
//!
//! Key roles:
//! - **Root key**: Ultimate authority; can ratify any action in Sovereign phase.

use thiserror::Error;

/// Errors relating to Kinetic global governance actions.
#[derive(Error, Debug, PartialEq, Eq)]
pub enum GovernanceError {
    /// **What**: The daemon started in Sovereign mode but the `SOVEREIGN_KEY_HEX` environment variable is missing.
    /// **Why**: The daemon requires the root public key at startup to verify incoming governance actions.
    /// **Fix**: Ensure the `SOVEREIGN_KEY_HEX` environment variable is set to a valid 64-character hex string.
    #[error("Missing SOVEREIGN_KEY_HEX environment variable")]
    MissingSovereignKey,

    /// **What**: The `SOVEREIGN_KEY_HEX` environment variable contains invalid characters or is incorrectly padded.
    /// **Why**: The daemon failed to decode the hex string into raw ML-DSA-65 bytes.
    /// **Fix**: Verify the key is exactly 64 valid hexadecimal characters.
    #[error("Malformed SOVEREIGN_KEY_HEX environment variable")]
    MalformedSovereignKey,

    /// **What**: The decoded ML-DSA-65 root key is the wrong byte length.
    /// **Why**: The post-quantum signature algorithm strictly requires a specific byte length for public keys.
    /// **Fix**: Ensure you are using a valid ML-DSA-65 public key generated by the Kinetic CLI.
    #[error("Invalid root key length")]
    KeyLengthMismatch,

    /// **What**: The proposed governance action is older than the current network head timestamp.
    /// **Why**: The node rejects historical actions to prevent time-delay and replay attacks.
    /// **Fix**: This action was discarded. If you are the issuer, ensure your local clock is synced via NTP before signing.
    #[error("Governance action is older than the current network state")]
    StaleProposal,

    /// **What**: A governance action with a specific ID has already been executed and recorded in the local state.
    /// **Why**: The network strictly deduplicates actions based on their cryptographic signature to prevent immediate replay attacks.
    /// **Fix**: This action was safely ignored. No further action is required.
    #[error("Governance action has already been executed")]
    AlreadyExecuted,

    /// **What**: A governance action was received, but the node is running in permissionless mode.
    /// **Why**: In permissionless testnets or specific deployments, global governance actions are universally rejected.
    /// **Fix**: The node safely dropped the message. Ensure you are targeting the correct network ID.
    #[error("Governance is disabled in permissionless mode")]
    GovernanceDisabled,

    /// **What**: The governance message signature failed cryptographic verification against the root key.
    /// **Why**: The payload was either tampered with in transit or signed by an unauthorized private key.
    /// **Fix**: The message was rejected. If you are the issuer, ensure you are signing with the correct ML-DSA-65 root private key.
    #[error("Invalid signature")]
    InvalidSignature,

    /// **What**: A prime name mapping or unmapping was attempted on a name that is not exactly 1 character long.
    /// **Why**: By protocol definition, Prime names (e.g., `a.kin`) are strictly reserved and must be exactly one character.
    /// **Fix**: Correct your governance payload to target a 1-character name.
    #[error("Prime name mappings must be exactly 1 character long")]
    InvalidPrimeLength,

    /// **What**: A protocol name mapping was attempted on a name that is not whitelisted in the Category 2 protocols list.
    /// **Why**: Category 2 names (e.g., `seed.kin`, `docs.kin`) are strictly defined in the protocol schema.
    /// **Fix**: Ensure your governance payload targets a valid, recognized protocol name.
    #[error("Protocol name mappings must target a valid Category 2 protocol name")]
    InvalidProtocolName,

    /// **What**: A governance action attempted to map a name that is already currently mapped.
    /// **Why**: The state transition is invalid. Overwriting an active mapping directly is forbidden to prevent accidental hijacking.
    /// **Fix**: You must explicitly unmap the name first by publishing a revocation action before remapping it.
    #[error("Name is already mapped, explicitly unmap it first")]
    AlreadyMapped,

    /// **What**: A governance action attempted to revoke or unmap a name that does not exist in the current state.
    /// **Why**: The state transition is invalid as there is no active mapping to remove.
    /// **Fix**: Verify the current governance state using the local REST API before issuing revocations.
    #[error("Name is not currently mapped")]
    NotMapped,

    /// **What**: The name payload in the governance action was unnormalized.
    /// **Why**: Payloads must be strictly normalized (no `.kin` suffix, strictly lowercase) before being signed to ensure deterministic verification.
    /// **Fix**: Use the `kinetic_types::names::normalize` function before signing your governance payload.
    #[error(
        "Name payloads in governance actions must be strictly normalized (no .kin suffix, lowercase, length checks)"
    )]
    UnnormalizedName,

    /// **What**: The daemon could not persist the updated governance state to disk.
    /// **Why**: The file system may be read-only, or the daemon process lacks necessary write permissions.
    /// **Fix**: Check disk space and permissions for the `base_dir/networks/nsp-salt_id/` directory.
    #[error("Failed to save modified governance state to disk")]
    StateSaveFailed,

    /// **What**: The local node successfully verified the action, but could not broadcast it to the P2P network.
    /// **Why**: The GossipSub publish operation failed due to a lack of connected peers or a saturated network queue.
    /// **Fix**: Verify your node is well-connected to the mesh before issuing administrative actions.
    #[error("Failed to publish Governance Message to P2P network")]
    P2pPublishFailed,

    /// **What**: A bootstrap seed node provided governance bytes that failed decoding or validation.
    /// **Why**: The seed node may be running an incompatible protocol version or attempting to distribute a malicious state.
    /// **Fix**: The node disconnected from the seed and will try another. Ensure your configured bootstrap nodes are trustworthy.
    #[error("Seed node provided invalid governance state bytes")]
    InvalidSeedState,

    /// **What**: The local governance JSON state file on disk is corrupted and cannot be parsed.
    /// **Why**: A previous write operation was interrupted by a power loss or crash, leaving partial JSON bytes.
    /// **Fix**: The daemon will refuse to start to avoid overwriting valid network state. You must manually delete the corrupted file and let it resync.
    #[error("Governance state corrupted")]
    StateCorrupted,

    /// **What**: The local governance file could not be read.
    /// **Why**: The file is missing, locked by another process, or has incorrect OS permissions.
    /// **Fix**: Ensure the daemon user has read access to the data directory.
    #[error("Failed to read Governance state file")]
    StateReadFailed,

    /// **What**: The node failed to pull the initial governance state from any bootstrap peers.
    /// **Why**: All configured bootstrap nodes are offline, unreachable, or returning invalid states.
    /// **Fix**: The node cannot join the network without a valid initial state. Check your internet connection and bootstrap configuration.
    #[error("Failed to fetch governance state from any bootstrap node")]
    BootstrapFetchFailed,
}

impl GovernanceError {
    /// Stable protocol error code. Part of the Kinetic error taxonomy.
    pub fn code(&self) -> &'static str {
        match self {
            Self::MissingSovereignKey => "KIN-ACN-001",
            Self::MalformedSovereignKey => "KIN-ACN-002",
            Self::GovernanceDisabled => "KIN-ACN-003",
            Self::KeyLengthMismatch => "KIN-ACN-004",
            Self::StaleProposal => "KIN-ACN-005",
            Self::AlreadyExecuted => "KIN-ACN-006",
            Self::InvalidSignature => "KIN-ACN-007",
            Self::InvalidPrimeLength => "KIN-ACN-008",
            Self::InvalidProtocolName => "KIN-ACN-009",
            Self::AlreadyMapped => "KIN-ACN-010",
            Self::NotMapped => "KIN-ACN-011",
            Self::UnnormalizedName => "KIN-ACN-012",
            Self::StateSaveFailed => "KIN-ACN-013",
            Self::P2pPublishFailed => "KIN-ACN-014",
            Self::InvalidSeedState => "KIN-ACN-015",
            Self::StateCorrupted => "KIN-ACN-016",
            Self::StateReadFailed => "KIN-ACN-017",
            Self::BootstrapFetchFailed => "KIN-ACN-018",
        }
    }

    /// RFC 7807 type URI for this error.
    pub fn error_type_uri(&self) -> String {
        format!("{}/errors/{}", "https://docs.kinetic.network", self.code())
    }

    /// Severity level for logging and monitoring.
    pub fn severity(&self) -> kinetic_types::error::Severity {
        match self {
            Self::MissingSovereignKey | Self::MalformedSovereignKey | Self::StateCorrupted => {
                kinetic_types::error::Severity::Critical
            }
            Self::StaleProposal | Self::AlreadyExecuted => kinetic_types::error::Severity::Info,
            Self::KeyLengthMismatch
            | Self::StateSaveFailed
            | Self::P2pPublishFailed
            | Self::StateReadFailed => kinetic_types::error::Severity::Error,
            Self::GovernanceDisabled
            | Self::InvalidSignature
            | Self::InvalidPrimeLength
            | Self::InvalidProtocolName
            | Self::AlreadyMapped
            | Self::NotMapped
            | Self::InvalidSeedState
            | Self::BootstrapFetchFailed
            | Self::UnnormalizedName => kinetic_types::error::Severity::Warning,
        }
    }

    /// Whether the client should offer a retry action.
    pub fn is_retryable(&self) -> bool {
        matches!(
            self,
            Self::InvalidSignature | Self::P2pPublishFailed | Self::BootstrapFetchFailed
        )
    }

    /// Clean user-facing message with no developer details.
    pub fn user_message(&self) -> String {
        match self {
            Self::MissingSovereignKey => "The SOVEREIGN_KEY_HEX environment variable is not set. This is a fatal configuration error.".to_string(),
            Self::MalformedSovereignKey => "The SOVEREIGN_KEY_HEX environment variable contains invalid characters and cannot be decoded.".to_string(),

            Self::KeyLengthMismatch => "The provided cryptographic key length is invalid.".to_string(),
            Self::StaleProposal => "The proposed governance action is too old and has been rejected to prevent replay attacks.".to_string(),
            Self::AlreadyExecuted => "The proposed governance action has already been executed on the network and cannot be replayed.".to_string(),

            Self::GovernanceDisabled => {
                "The network is operating in permissionless mode where governance actions are universally rejected.".to_string()
            }
            Self::InvalidSignature => {
                "The message signature does not cryptographically match the configured root key.".to_string()
            }
            Self::InvalidPrimeLength => "Prime names governed by this action must be exactly 1 character long.".to_string(),
            Self::InvalidProtocolName => "Protocol names governed by this action must be valid Category 2 names.".to_string(),
            Self::AlreadyMapped => "The requested name is already mapped. It must be explicitly unmapped first.".to_string(),
            Self::NotMapped => "The requested name is not currently mapped.".to_string(),
            Self::UnnormalizedName => "The name payload must be strictly normalized (no .kin suffix, lowercase).".to_string(),
            Self::StateSaveFailed => "Failed to save the modified governance state to disk.".to_string(),
            Self::P2pPublishFailed => "Failed to broadcast the governance message to the P2P network.".to_string(),
            Self::InvalidSeedState => "A bootstrap seed node provided an invalid governance state.".to_string(),
            Self::StateCorrupted => "The local governance state file is corrupted.".to_string(),
            Self::StateReadFailed => "Failed to read the local governance state file from disk.".to_string(),
            Self::BootstrapFetchFailed => "Failed to pull governance state from bootstrap nodes.".to_string(),
        }
    }
}
