#![no_main]

use arbitrary::Arbitrary;
use kinetic_core::traits::VdfEngine;
use kinetic_core::types::{Commitment, VdfProof};
use kinetic_vdf::RsaVdfEngine;
use libfuzzer_sys::fuzz_target;

#[derive(Arbitrary, Debug)]
struct FuzzInput {
    challenge_bytes: [u8; 32],
    verify_iterations: u64,
    eval_iterations: u16, // Keep eval capped to max 65k to prevent fuzzer from hanging on time-delay
    proof_bytes: Vec<u8>,
}

fuzz_target!(|data: FuzzInput| {
    let engine = RsaVdfEngine::new();
    let challenge = Commitment {
        hash: data.challenge_bytes,
    };

    // --- 1. FUZZ THE VERIFIER ---
    // Feed completely arbitrary garbage bytes and extreme iteration counts into verify().
    // It must NEVER panic, and should cleanly return Err(InvalidProof) or Ok(false).
    let random_proof = VdfProof {
        proof_bytes: data.proof_bytes,
    };
    let _ = engine.verify(&challenge, &random_proof, data.verify_iterations);

    // --- 2. FUZZ THE PROVER MATH ---
    // Run evaluate() with the capped eval_iterations.
    // If the challenge is the degenerate all-zero array, or iterations=0, it will return Err.
    if let Ok(valid_proof) = engine.evaluate(&challenge, data.eval_iterations as u64) {
        // If it successfully evaluated, it MUST verify successfully against itself.
        let is_valid = engine
            .verify(&challenge, &valid_proof, data.eval_iterations as u64)
            .unwrap_or(false);

        // Sanity check: verify should always return true for a valid proof generated by evaluate.
        assert!(is_valid, "Valid proof failed to verify itself! iterations: {}", data.eval_iterations);
    }
});
