[package]
name = "kinetic-forge"
description = "CLI wizard for bootstrapping and scaffolding isolated private Kinetic networks"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
dialoguer.workspace = true
serde_json.workspace = true
toml_edit.workspace = true
