[package]
name = "kinetic-daemon-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys.workspace = true
reqwest.workspace = true
subtle.workspace = true

[dependencies.kinetic-daemon]
path = ".."

[[bin]]
name = "proxy_url_parser"
path = "fuzz_targets/proxy_url_parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "api_auth_token"
path = "fuzz_targets/api_auth_token.rs"
test = false
doc = false
bench = false

[workspace]

[lints]
workspace = true
