use serde::{Deserialize, Serialize};

/// The Kinetic top-level domain (without the leading dot).
pub const TLD: &str = "kin";
/// The Kinetic top-level domain with a leading dot.
pub const DOT_TLD: &str = ".kin";

/// Normalizes a name by ensuring it is lowercase and ends with exactly one `DOT_TLD`.
pub fn normalize_name(name: &str) -> String {
    let mut norm = name.to_lowercase();
    while norm.ends_with('.') {
        norm.pop();
    }
    if !norm.ends_with(DOT_TLD) {
        norm.push_str(DOT_TLD);
    }
    norm
}

/// All reserved second-level label combinations that form multi-part
/// Kinetic TLDs (e.g. `co.uk.kin`, `app.kin`).
pub const KINETIC_TLDS: &[&str] = &[
    "co.uk.kin",
    "uk.kin",
    "co.kin",
    "id.kin",
    "app.kin",
    "dapp.kin",
    TLD,
];

/// Validates that a name is exactly an apex domain (e.g., `saif.kin` and not `blog.saif.kin`)
pub fn is_valid_apex_name(name: &str) -> bool {
    let norm = normalize_name(name);

    // DNS specification limits labels to 63 characters and total length to 253.
    if norm.len() > 253 || norm.is_empty() {
        return false;
    }
    for part in norm.split('.') {
        if part.len() > 63 || part.is_empty() {
            return false;
        }
    }

    let apex = extract_apex_domain(&norm);
    norm == apex
}

/// Extracts the apex domain from a potentially subdomain string.
/// For example, `blog.saif.kin` -> `saif.kin`
/// `blog.saif.co.uk.kin` -> `saif.co.uk.kin`
pub fn extract_apex_domain(name: &str) -> String {
    let norm = normalize_name(name);

    for tld in KINETIC_TLDS {
        if norm.ends_with(&format!(".{}", tld)) || norm == *tld {
            let without_tld = norm.strip_suffix(&format!(".{}", tld)).unwrap_or(&norm);
            if without_tld.is_empty() || without_tld == norm {
                return norm;
            }
            let parts: Vec<&str> = without_tld.split('.').collect();
            let apex_label = parts.last().unwrap_or(&"");
            return format!("{}.{}", apex_label, tld);
        }
    }

    // Fallback
    let parts: Vec<&str> = norm.split('.').collect();
    if parts.len() >= 2 {
        let last_two = &parts[parts.len() - 2..];
        format!("{}.{}", last_two[0], last_two[1])
    } else {
        norm
    }
}

/// Maximum age of a VDF proof in drand rounds (~1 year at 30 s/round).
pub const RESQUARING_EPOCH_ROUNDS: u64 = 1_051_200;

/// Maximum allowed byte size for a Decentralized DNS Zone payload (64 KiB).
pub const MAX_PAYLOAD_SIZE: usize = 65_536;

/// A SHA-256 commitment hash used as the VDF challenge input.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Commitment {
    /// The 32-byte SHA-256 hash acting as the commitment.
    pub hash: [u8; 32],
}

/// An output generated by a Verifiable Delay Function.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VdfProof {
    /// The serialized mathematical proof (e.g., from the Chia Class Group VDF)
    pub proof_bytes: Vec<u8>,
}

/// A commitment used to pre-announce a name registration without revealing the name.
///
/// Sent to the daemon before the [`Reveal`] to establish a time-lock.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommitRequest {
    /// The normalised `.kin` name being committed to.
    pub name: String,
    /// The SHA-256 commitment hash.
    pub commitment: Commitment,
}

fn default_protocol_version() -> u8 {
    2
}

/// A prior VDF proof that is carried forward during a name renewal,
/// linking the renewal to the previous ownership cycle.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PreviousProof {
    /// The random salt from the previous registration.
    pub salt: [u8; 32],
    /// The drand pulse round used in the previous registration.
    pub drand_pulse: u64,
    /// The drand randomness hex string from the previous registration.
    pub drand_randomness: String,
    /// The number of VDF iterations from the previous registration.
    pub iterations: u64,
    /// The VDF proof from the previous registration.
    pub vdf_proof: VdfProof,
    /// The owner's signature over the previous proof bytes.
    pub signature: Vec<u8>,
}

impl PreviousProof {
    /// Serializes the previous proof components that are covered by the owner's signature.
    pub fn proof_bytes(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.salt);
        bytes.extend_from_slice(&self.drand_pulse.to_be_bytes());
        bytes.extend_from_slice(self.drand_randomness.as_bytes());
        bytes.extend_from_slice(&self.iterations.to_be_bytes());
        bytes.extend_from_slice(&self.vdf_proof.proof_bytes);
        bytes.extend_from_slice(&self.signature);
        bytes
    }
}

/// A request that finalizes a domain registration by providing the VDF proof and mapping payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Reveal {
    /// Domain separation protocol version to prevent replay attacks.
    #[serde(default = "default_protocol_version")]
    pub protocol_version: u8,
    /// The human-readable handle being registered
    pub name: String,
    /// The actual data bound to this name (e.g. an IP address)
    pub payload: Vec<u8>,
    /// The cryptographic salt used to prevent dictionary attacks prior to reveal
    pub salt: [u8; 32],
    /// The specific Drand pulse round number bound to this commitment
    pub drand_pulse: u64,
    /// The hex-encoded randomness string from the drand pulse.
    pub drand_randomness: String,
    /// The number of iterations executed for the VDF.
    pub iterations: u64,
    /// The VDF proof solving the sequential puzzle
    pub vdf_proof: VdfProof,
    /// The public key claiming this name
    pub pubkey: Vec<u8>,
    /// The signature of the reveal tuple to prevent front-running hijacking
    pub signature: Vec<u8>,

    /// The optional proof from a previous ownership cycle, used for renewals.
    pub previous_proof: Option<PreviousProof>,
    /// The public key of the miner who produced a point-spend proof, if any.
    pub miner_pubkey: Option<Vec<u8>>,
    /// The number of accumulated points spent to reduce the VDF difficulty.
    pub points_spent: Option<u64>,
}

impl Reveal {
    /// Validates that the [`Reveal`] is well-formed: correct protocol version,
    /// valid apex name, and payload within size limits.
    pub fn validate(&self) -> Result<(), crate::error::KineticError> {
        if self.protocol_version != 2 {
            return Err(crate::error::KineticError::Internal(format!(
                "Invalid protocol version {}. Only protocol version 2 is supported.",
                self.protocol_version
            )));
        }

        if !crate::types::is_valid_apex_name(&self.name) {
            return Err(crate::error::KineticError::Internal(format!(
                "Invalid name '{}'. Only apex domains are allowed.",
                self.name
            )));
        }

        if self.payload.len() > MAX_PAYLOAD_SIZE {
            return Err(crate::error::KineticError::Internal(format!(
                "Payload size {} exceeds MAX_PAYLOAD_SIZE {}",
                self.payload.len(),
                MAX_PAYLOAD_SIZE
            )));
        }
        Ok(())
    }

    /// Serialises the fields that are covered by the owner's Ed25519 signature.
    ///
    /// The protocol version is always the first byte, providing a domain
    /// separator against cross-version replay attacks.
    pub fn signable_bytes(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.push(self.protocol_version);
        bytes.extend_from_slice(self.name.as_bytes());
        bytes.extend_from_slice(&self.payload);
        bytes.extend_from_slice(&self.salt);
        bytes.extend_from_slice(&self.drand_pulse.to_be_bytes());
        bytes.extend_from_slice(self.drand_randomness.as_bytes());
        bytes.extend_from_slice(&self.iterations.to_be_bytes());
        bytes.extend_from_slice(&self.vdf_proof.proof_bytes);
        bytes.extend_from_slice(&self.pubkey);

        if let Some(prev) = &self.previous_proof {
            bytes.extend_from_slice(&prev.proof_bytes());
        }
        if let Some(miner_pk) = &self.miner_pubkey {
            bytes.extend_from_slice(miner_pk);
        }
        if let Some(points) = self.points_spent {
            bytes.extend_from_slice(&points.to_be_bytes());
        }

        bytes
    }
}

/// A periodic liveness signal published to the DHT by a domain owner.
///
/// If a heartbeat is not observed for a configurable number of drand rounds,
/// the domain is considered hibernated and eligible for takeover.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Heartbeat {
    /// The normalised `.kin` name being kept alive.
    pub name: String,
    /// The most recent drand pulse round observed by the owner.
    pub latest_drand_pulse: u64,
    /// Ed25519 signature of `name + latest_drand_pulse`.
    pub signature: Vec<u8>,
}

impl Heartbeat {
    /// Returns the bytes that are covered by the Ed25519 signature.
    pub fn signable_bytes(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(self.name.as_bytes());
        bytes.extend_from_slice(&self.latest_drand_pulse.to_be_bytes());
        bytes
    }
}

/// A VDF-proven record published by a domain owner who wants to pause
/// ("hibernate") their domain without losing ownership.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Hibernation {
    /// The normalised `.kin` name being hibernated.
    pub name: String,
    /// The drand pulse round used to compute the hibernation VDF.
    pub drand_pulse: u64,
    /// The drand randomness hex string for the given pulse.
    pub drand_randomness: String,
    /// The number of VDF iterations solved.
    pub iterations: u64,
    /// The VDF proof demonstrating the elapsed time.
    pub vdf_proof: VdfProof,
    /// The owner's Ed25519 public key.
    pub pubkey: Vec<u8>,
    /// A random salt preventing reuse of prior proofs.
    pub salt: [u8; 32],
    /// Ed25519 signature over the signable fields.
    pub signature: Vec<u8>,
}

impl Hibernation {
    /// Returns the bytes covered by the Ed25519 signature.
    pub fn signable_bytes(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(b"HIBERNATION");
        bytes.extend_from_slice(self.name.as_bytes());
        bytes.extend_from_slice(&self.drand_pulse.to_be_bytes());
        bytes.extend_from_slice(self.drand_randomness.as_bytes());
        bytes.extend_from_slice(&self.iterations.to_be_bytes());
        bytes.extend_from_slice(&self.vdf_proof.proof_bytes);
        bytes.extend_from_slice(&self.pubkey);
        bytes.extend_from_slice(&self.salt);
        bytes
    }
}

/// A mobile-device request to delegate ownership of a `.kin` name to another key.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DelegationRequest {
    /// The `.kin` name being delegated.
    pub name: String,
    /// The serialised DNS zone payload to publish under the delegated key.
    pub payload: Vec<u8>,
    /// The Ed25519 public key of the delegatee.
    pub delegated_to_pubkey: Vec<u8>,
    /// The mobile device's ephemeral public key.
    pub mobile_pubkey: Vec<u8>,
    /// Signature by the original owner.
    pub signature: Vec<u8>,
    /// Hashcash nonce for rate-limiting.
    pub hashcash_nonce: u64,
}

impl DelegationRequest {
    /// Returns the bytes covered by the owner's Ed25519 signature.
    pub fn signable_bytes(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(b"DELEGATION");
        bytes.extend_from_slice(self.name.as_bytes());
        bytes.extend_from_slice(&self.payload);
        bytes.extend_from_slice(&self.delegated_to_pubkey);
        bytes.extend_from_slice(&self.hashcash_nonce.to_le_bytes());
        bytes
    }
}

/// A request sent from the daemon to the VDF worker thread to begin computation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VdfJobRequest {
    /// The SHA-256 challenge hash derived from the commit.
    pub challenge_hash: [u8; 32],
    /// The length of the name in bytes, used to scale difficulty.
    pub name_length: u8,
    /// Hashcash nonce for rate-limiting.
    pub hashcash_nonce: u64,
    /// The drand pulse round that scoped this job.
    pub drand_pulse: u64,
}

/// The number of independent DHT keys used to store each record,
/// providing eclipse-attack resistance.
pub const M_REDUNDANCY: u8 = 32;
/// The minimum allowed PoW difficulty in leading zero bits.
pub const MIN_DIFFICULTY: u32 = 20;

/// Deterministically derive the `M` Kademlia DHT storage keys for a given name.
/// This prevents single-key eclipse attacks.
pub fn derive_storage_keys(name: &str) -> Vec<[u8; 32]> {
    use sha2::{Digest, Sha256};
    let normalized = normalize_name(name);
    let mut keys = Vec::with_capacity(M_REDUNDANCY as usize);

    for i in 0..M_REDUNDANCY {
        let mut hasher = Sha256::new();
        hasher.update(normalized.as_bytes());
        hasher.update([i]);
        hasher.update(b"kinetic-dht-v1");

        let result = hasher.finalize();
        let mut key = [0u8; 32];
        key.copy_from_slice(&result);
        keys.push(key);
    }
    keys
}

/// Derive the `M` Kademlia DHT keys for heartbeat liveness signals.
/// These are deliberately separate from `derive_storage_keys` so heartbeat records
/// never overwrite or pollute the Reveal keyspace used by resolvers.
pub fn derive_heartbeat_keys(name: &str) -> Vec<[u8; 32]> {
    use sha2::{Digest, Sha256};
    let normalized = normalize_name(name);
    let mut keys = Vec::with_capacity(M_REDUNDANCY as usize);

    for i in 0..M_REDUNDANCY {
        let mut hasher = Sha256::new();
        hasher.update(b"kinetic-hb-v1"); // distinct domain separator
        hasher.update(normalized.as_bytes());
        hasher.update([i]);

        let result = hasher.finalize();
        let mut key = [0u8; 32];
        key.copy_from_slice(&result);
        keys.push(key);
    }
    keys
}

/// Loads or generates the daemon's persistent Ed25519 signing key.
///
/// The key is stored at `~/.config/kinetic/identity.key` (or the path set by
/// `KINETIC_KEY_PATH`). If the file is missing, a new key is generated and
/// written atomically. If the file is found but has the wrong length, an error
/// is returned to prevent silent key corruption.
#[cfg(not(target_arch = "wasm32"))]
pub fn load_or_create_keypair(filename: &str) -> Result<ed25519_dalek::SigningKey, crate::error::KineticError> {
    use directories::ProjectDirs;
    use std::fs;
    use std::path::PathBuf;

    let key_path = std::env::var("KINETIC_KEY_PATH")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            ProjectDirs::from("com", "kinetic", "kinetic")
                .map(|d| d.config_dir().join(filename))
                .unwrap_or_else(|| {
                    std::env::current_dir()
                        .unwrap_or_else(|_| PathBuf::from("."))
                        .join(format!(".kinetic/{}", filename))
                })
        });

    if let Some(parent) = key_path.parent() {
        let _ = fs::create_dir_all(parent);
    }

    if key_path.exists() {
        let bytes = fs::read(&key_path)?;
        if bytes.len() == 32 {
            let mut array = [0u8; 32];
            array.copy_from_slice(&bytes);
            return Ok(ed25519_dalek::SigningKey::from_bytes(&array));
        } else {
            return Err(crate::error::KineticError::CryptoError(
                format!("Identity file is corrupted! Expected 32 bytes, found {}. Please restore from a backup or manually delete the file to generate a new identity.", bytes.len())
            ));
        }
    }

    let mut bytes = [0u8; 32];
    if getrandom::getrandom(&mut bytes).is_err() {
        return Err(crate::error::KineticError::CryptoError(
            "Random generation failed".to_string(),
        ));
    }
    let signing_key = ed25519_dalek::SigningKey::from_bytes(&bytes);

    // Atomic write to prevent file corruption during generation
    let tmp_path = key_path.with_extension("tmp");
    fs::write(&tmp_path, signing_key.to_bytes())?;
    fs::rename(tmp_path, &key_path)?;

    Ok(signing_key)
}

#[cfg(target_arch = "wasm32")]
/// Stub implementation for loading or creating a keypair in Wasm
pub fn load_or_create_keypair(_filename: &str) -> Result<ed25519_dalek::SigningKey, crate::error::KineticError> {
    Err(crate::error::KineticError::Internal(
        "Key generation via filesystem is not supported in Wasm. Provide a key manually."
            .to_string(),
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_derive_storage_keys() {
        let keys = derive_storage_keys(&format!("{}{}", "saif", crate::types::DOT_TLD));
        assert_eq!(keys.len(), 32);

        // Ensure determinism
        let keys2 = derive_storage_keys("SAIF.KIN");
        assert_eq!(keys, keys2);

        // Ensure keys are unique
        for i in 0..keys.len() {
            for j in i + 1..keys.len() {
                assert_ne!(keys[i], keys[j]);
            }
        }
    }

    #[test]
    fn test_normalize_name() {
        assert_eq!(
            normalize_name("SAIF.KIN"),
            format!("{}{}", "saif", crate::types::DOT_TLD)
        );
        assert_eq!(
            normalize_name("saif..."),
            format!("{}{}", "saif", crate::types::DOT_TLD)
        );
        assert_eq!(
            normalize_name("saif"),
            format!("{}{}", "saif", crate::types::DOT_TLD)
        );
        assert_eq!(
            normalize_name("blog.saif.kin."),
            format!("{}{}", "blog.saif", crate::types::DOT_TLD)
        );
    }

    #[test]
    fn test_is_valid_apex_name() {
        assert!(is_valid_apex_name(&format!(
            "{}{}",
            "saif",
            crate::types::DOT_TLD
        )));
        assert!(is_valid_apex_name("saif")); // gets normalized
        assert!(!is_valid_apex_name(&format!(
            "{}{}",
            "blog.saif",
            crate::types::DOT_TLD
        )));
    }

    #[test]
    fn test_extract_apex_domain() {
        assert_eq!(
            extract_apex_domain(&format!("{}{}", "blog.saif", crate::types::DOT_TLD)),
            format!("{}{}", "saif", crate::types::DOT_TLD)
        );
        assert_eq!(
            extract_apex_domain(&format!("{}{}", "saif", crate::types::DOT_TLD)),
            format!("{}{}", "saif", crate::types::DOT_TLD)
        );
        assert_eq!(
            extract_apex_domain(&format!("{}{}", "api.v1.saif", crate::types::DOT_TLD)),
            format!("{}{}", "saif", crate::types::DOT_TLD)
        );
    }

    #[test]
    fn test_signable_bytes() {
        let reveal = Reveal {
            protocol_version: 2,
            name: format!("{}{}", "test", crate::types::DOT_TLD),
            payload: vec![1, 2, 3],
            salt: [0u8; 32],
            drand_pulse: 100,
            drand_randomness: "randomness".to_string(),
            iterations: 1000,
            vdf_proof: VdfProof {
                proof_bytes: vec![4, 5, 6],
            },
            pubkey: vec![7, 8, 9],
            signature: vec![],
            previous_proof: None,
            miner_pubkey: None,
            points_spent: None,
        };
        let bytes = reveal.signable_bytes();
        assert_eq!(bytes[0], 2); // Protocol version
        assert!(bytes.len() > 10);
    }
}

/// Represents a Decentralized DNS Zone stored in the DHT payload
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct DnsZone {
    /// Map from subdomain label (e.g. `"@"`, `"www"`) to a list of DNS records.
    #[serde(default)]
    pub records: std::collections::HashMap<String, Vec<DnsRecord>>,
}

/// A single DNS record stored in a [`DnsZone`].
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", content = "value")]
pub enum DnsRecord {
    /// An IPv4 address record.
    A(String),
    /// An IPv6 address record.
    AAAA(String),
    /// A canonical name alias.
    CNAME(String),
    /// A text record.
    TXT(String),
    /// A libp2p Peer ID for P2P proxy routing.
    PeerId(String),
    /// A Kinetic Identity Document (KID) DID string.
    KID(String),
}

/// A dynamic routing record to allow infrastructure hosts with static identities
/// to point to ephemeral PoW-compliant Peer IDs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HostRoutingRecord {
    /// The permanent Host Identity (usually the static PeerId string)
    pub host_id: String,
    /// The current 12-hour PoW-compliant temporary PeerId
    pub current_peer_id: String,
    /// The unix timestamp in seconds when this record was generated
    pub timestamp: u64,
    /// The cryptographic signature of `host_id + current_peer_id + timestamp`
    /// signed by the permanent Host Key
    pub signature: Vec<u8>,
}

impl HostRoutingRecord {
    /// Returns the bytes covered by the permanent host key's Ed25519 signature.
    pub fn signable_bytes(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(self.host_id.as_bytes());
        bytes.extend_from_slice(self.current_peer_id.as_bytes());
        bytes.extend_from_slice(&self.timestamp.to_be_bytes());
        bytes
    }
}

impl DnsZone {
    /// Parses a raw JSON `payload` bytes slice into a [`DnsZone`].
    ///
    /// Rejects payloads with JSON nesting depth > 10 to prevent stack
    /// overflow attacks on resource-constrained devices.
    pub fn parse_payload(payload: &[u8]) -> Result<Self, crate::error::KineticError> {
        // Prevent deeply nested JSON payloads from overflowing the stack on small mobile threads.
        // A DnsZone schema is flat (max depth ~4), so anything > 10 is malicious.
        let mut depth = 0;
        let mut in_string = false;
        let mut escape = false;
        for &b in payload {
            if escape {
                escape = false;
                continue;
            }
            match b {
                b'"' => in_string = !in_string,
                b'\\' if in_string => escape = true,
                b'{' | b'[' if !in_string => {
                    depth += 1;
                    if depth > 10 {
                        return Err(crate::error::KineticError::Internal(
                            "Payload rejected: JSON nested too deeply".to_string(),
                        ));
                    }
                }
                b'}' | b']' if !in_string && depth > 0 => {
                    depth -= 1;
                }
                _ => {}
            }
        }

        serde_json::from_slice::<DnsZone>(payload).map_err(crate::error::KineticError::ParseError)
    }
}

#[cfg(test)]
mod zone_tests {
    use super::*;

    #[test]
    fn test_parse_payload() {
        let json = r#"{"records": {"@": [{"type": "PeerId", "value": "12D3K"}]}}"#;
        let zone = DnsZone::parse_payload(json.as_bytes()).unwrap();
        if let Some(records) = zone.records.get("@") {
            assert_eq!(records.len(), 1);
            if let DnsRecord::PeerId(ref pid) = records[0] {
                assert_eq!(pid, "12D3K");
            } else {
                panic!("Expected PeerId");
            }
        } else {
            panic!("Expected @ record");
        }
    }
}
