[package]
name = "kinetic-host"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "The HTTP-to-P2P load balancing proxy and CDN edge node for the Kinetic Network."
readme = "README.md"

[dependencies]
anyhow.workspace = true
axum.workspace = true
bytes.workspace = true
clap = { workspace = true, features = ["derive"] }
ed25519-dalek.workspace = true
futures-util = "0.3"
http-body-util.workspace = true
kinetic-core = { path = "../kinetic-core" }
kinetic-local = { path = "../kinetic-local" }
kinetic-network = { path = "../kinetic-network" }
kinetic-storage = { path = "../kinetic-storage" }
kinetic-types = { path = "../kinetic-types" }
kinetic-vdf = { path = "../kinetic-vdf" }
libp2p = { workspace = true, features = ["ed25519", "tokio", "macros"] }
percent-encoding.workspace = true
reqwest = { workspace = true, features = ["stream"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
service-manager.workspace = true
tokio = { workspace = true, features = ["net"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
proptest.workspace = true
