#!/bin/bash
#
# entrypoint.sh — Container startup script for kinetic-sim (ContainerLab)
#
# Usage (set by topology.clab.yml):
#   bash /entrypoint.sh node   <index>
#   bash /entrypoint.sh daemon <index>
#   bash /entrypoint.sh host   <index>
#
# Environment assumptions:
#   - /sim-data/<role><index>/config.toml has been pre-generated by setup_sim.py
#   - /shared-volume is a shared podman volume (for the PoW mining mutex)
#   - All kinetic binaries are bind-mounted to /usr/local/bin/
#

ROLE=$1
INDEX=$2

echo "[$(date)] Starting container: role=$ROLE index=$INDEX"

# ── Common: copy per-container config ────────────────────────────────────────
mkdir -p ~/.config/kinetic
cp /sim-data/config.toml ~/.config/kinetic/config.toml

# ─────────────────────────────────────────────────────────────────────────────
# NODE
# ─────────────────────────────────────────────────────────────────────────────
if [ "$ROLE" == "node" ]; then
    echo "[Node $INDEX] Copying static network keypair..."
    cp /sim-data/static_network_key.bin ~/.config/kinetic/static_network_key.bin

    echo "[Node $INDEX] Starting kinetic-node..."
    exec kinetic-node 2>&1
fi

# ─────────────────────────────────────────────────────────────────────────────
# Shared: PoW mining mutex
# Ensures containers mine their S/Kademlia keypair one at a time,
# preventing all 40 processes from pegging all CPU cores simultaneously.
# ─────────────────────────────────────────────────────────────────────────────
echo "[${ROLE} ${INDEX}] Waiting for PoW mining lock..."
LOCK_DIR=/shared-volume/mining.lock

# Retry acquiring the lock every 3 seconds
while ! mkdir "$LOCK_DIR" 2>/dev/null; do
    sleep 3
done
echo "[${ROLE} ${INDEX}] Mining lock acquired!"

# ─────────────────────────────────────────────────────────────────────────────
# DAEMON
# ─────────────────────────────────────────────────────────────────────────────
if [ "$ROLE" == "daemon" ]; then
    echo "[Daemon $INDEX] Starting kinetic-daemon in background..."
    kinetic-daemon start > /tmp/daemon.log 2>&1 &
    DAEMON_PID=$!

    echo "[Daemon $INDEX] Waiting for P2P architecture to wire..."
    TIMEOUT=120
    ELAPSED=0
    while ! grep -q "P2P Network architecture wired" /tmp/daemon.log 2>/dev/null; do
        sleep 1
        ELAPSED=$((ELAPSED + 1))
        if [ $ELAPSED -ge $TIMEOUT ]; then
            echo "[Daemon $INDEX] ERROR: P2P did not wire within ${TIMEOUT}s. Aborting."
            # Release the lock so next container can try
            rmdir "$LOCK_DIR" 2>/dev/null
            exit 1
        fi
    done

    echo "[Daemon $INDEX] P2P wired! Releasing lock for next container..."
    rmdir "$LOCK_DIR" 2>/dev/null

    # ── Full lifecycle (the orchestrator drives this via kinetic-cli exec) ──
    # The orchestrator.py calls `podman exec` to run these commands at the
    # right moment in the causal phase sequence. We just keep the daemon alive.
    echo "[Daemon $INDEX] Daemon is live. Waiting for orchestrator instructions..."
    wait $DAEMON_PID
fi

# ─────────────────────────────────────────────────────────────────────────────
# HOST
# ─────────────────────────────────────────────────────────────────────────────
if [ "$ROLE" == "host" ]; then
    echo "[Host $INDEX] Starting kinetic-host in background..."
    kinetic-host > /tmp/host.log 2>&1 &
    HOST_PID=$!

    echo "[Host $INDEX] Waiting for P2P architecture to wire..."
    TIMEOUT=120
    ELAPSED=0
    while ! grep -q "P2P Network architecture wired" /tmp/host.log 2>/dev/null; do
        sleep 1
        ELAPSED=$((ELAPSED + 1))
        if [ $ELAPSED -ge $TIMEOUT ]; then
            echo "[Host $INDEX] ERROR: P2P did not wire within ${TIMEOUT}s. Aborting."
            rmdir "$LOCK_DIR" 2>/dev/null
            exit 1
        fi
    done

    echo "[Host $INDEX] P2P wired! Releasing lock for next container..."
    rmdir "$LOCK_DIR" 2>/dev/null

    echo "[Host $INDEX] Scaffolding web directory..."
    mkdir -p /var/www

    echo "[Host $INDEX] Starting HTTP backend on port 80..."
    python3 -m http.server 80 --directory /var/www > /tmp/http.log 2>&1 &

    echo "[Host $INDEX] Host is fully live. Serving proxy traffic..."
    wait $HOST_PID
fi
