//! CLI commands for submitting, signing, and managing post-quantum Kinetic network governance proposals.

use clap::Subcommand;
use kinetic_core::config::KineticConfig;
use kinetic_core::governance::SignedGovernanceMessage;
use reqwest::Client;
use std::path::PathBuf;

#[derive(Subcommand)]
pub enum GovernanceCommands {
    /// Broadcast a pre-signed governance JSON file generated by kinetic-OS
    Broadcast {
        /// Path to the signed_action.json file
        #[arg(long)]
        file: PathBuf,
    },
}

/// Processes a governance CLI command, signs the action, and publishes it to the network.
///
/// # Errors
/// Returns an `anyhow::Error` if:
/// - Target keys cannot be parsed or decoded from hex.
/// - Pre-flight validation against mirror manifest files fails.
/// - The local governance identity keypair cannot be loaded.
/// - The daemon API cannot be reached or returns an error.
/// - The governance message signature fails to generate.
pub async fn handle_governance_command(
    cmd: GovernanceCommands,
    config: &KineticConfig,
    client: &Client,
) -> anyhow::Result<()> {
    let msg: SignedGovernanceMessage = match cmd {
        GovernanceCommands::Broadcast { file } => {
            let msg_str = std::fs::read_to_string(&file).map_err(|e| {
                anyhow::anyhow!("Failed to read governance file {}: {}", file.display(), e)
            })?;
            serde_json::from_str(&msg_str)
                .map_err(|e| anyhow::anyhow!("Failed to parse governance JSON: {}", e))?
        }
    };

    // Publish to the daemon
    let port = config.daemon.api_port;
    let token =
        std::fs::read_to_string(kinetic_local::config::get_api_tokens_dir().join("admin.token"))?;

    let publish_url = format!(
        "http://{}:{}/publish-governance",
        config.daemon.bind_ip, port
    );
    let publish_resp = client
        .post(&publish_url)
        .header("Authorization", format!("Bearer {}", token.trim()))
        .json(&msg)
        .send()
        .await?;

    if publish_resp.status().is_success() {
        println!("Successfully published governance action to the Kinetic Network!");
    } else {
        let err_text = publish_resp.text().await?;
        println!("Failed to publish governance action: {}", err_text);
    }

    Ok(())
}
