[package]
name = "kinetic-storage-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
tempfile = "3.27.0"
kinetic-core = { path = "../../kinetic-core" }

[dependencies.kinetic-storage]
path = ".."

[[bin]]
name = "storage_ops"
path = "fuzz_targets/storage_ops.rs"
test = false
doc = false
bench = false
