[package]
name = "kinetic-storage-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys.workspace = true
tempfile.workspace = true
kinetic-core.workspace = true

[dependencies.kinetic-storage]
path = ".."

[[bin]]
name = "storage_ops"
path = "fuzz_targets/storage_ops.rs"
test = false
doc = false
bench = false

[lints]
workspace = true
