//! Verifiable Delay Function (VDF) commitments, proofs, reveals, and signature verification.
//!
//! Provides the core wire types for the Kinetic two-phase name registration protocol:
//!
//! 1. **Phase 1 (Commitment)**: Submitting a blind SHA-256 [`Commitment`] hash to claim registration priority.
//! 2. **Phase 2 (Reveal)**: Revealing name metadata, salt, drand randomness, and the computed
//!    [`VdfProof`] inside a [`Reveal`] structure verified with post-quantum ML-DSA-65 signatures.

#![allow(clippy::collapsible_if)]
use kinetic_primitives::kinetic_keypair::IdentityPubKey;
use serde::{Deserialize, Serialize};

fn default_protocol_version() -> u8 {
    1
}

/// Cryptographic SHA-256 hash commitment to a registration request.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Commitment {
    /// 32-byte SHA-256 commitment hash.
    pub hash: [u8; 32],
}

impl Commitment {
    /// Canonically derives the VDF challenge hash.
    ///
    /// This is the SINGLE source of truth for generating VDF challenges across
    /// the Kinetic network. It cryptographically binds the network salt, the target
    /// name, the user's random salt, the compressed Drand randomness, and the
    /// user's public key.
    pub fn derive(
        network_salt: &[u8; 32],
        name: &str,
        user_salt: &[u8; 32],
        drand_signature_bytes: &[u8],
        pubkey: &IdentityPubKey,
    ) -> Self {
        // Compress the 96-byte BLS12-381 G2 Drand signature into a 32-byte hash
        let drand_rand = kinetic_primitives::sha256_hash(drand_signature_bytes);

        // Construct the unified VDF challenge
        let mut data = Vec::with_capacity(
            network_salt.len() + name.len() + user_salt.len() + drand_rand.len() + pubkey.0.len(),
        );
        data.extend_from_slice(network_salt);
        data.extend_from_slice(name.as_bytes());
        data.extend_from_slice(user_salt);
        data.extend_from_slice(&drand_rand);
        data.extend_from_slice(&pubkey.0);

        Self {
            hash: kinetic_primitives::sha256_hash(&data),
        }
    }
}

/// Raw proof bytes generated by the Verifiable Delay Function engine.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VdfProof {
    /// Raw VDF evaluation proof bytes.
    pub proof_bytes: Vec<u8>,
}

/// Initial commitment submission request payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommitRequest {
    /// Target `.kin` name.
    pub name: String,
    /// Cryptographic commitment.
    pub commitment: Commitment,
}

/// Previous VDF proof link in a chained name renewal proof sequence.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct PreviousProof {
    /// 32-byte salt used in the previous proof generation.
    pub salt: [u8; 32],
    /// Associated KineticTime kyn number from prior registration.
    pub kyn: u64,
    /// Hex-encoded KineticTime BLS12-381 G2 signature from prior registration.
    pub drand_signature: String,
    /// Number of VDF iterations completed in prior registration.
    pub iterations: u64,
    /// Embedded VDF proof bytes.
    pub vdf_proof: VdfProof,
    /// Cryptographic signature of the previous proof generated by the IdentityPrivKey.
    pub identity_signature: Vec<u8>,
}

impl PreviousProof {
    /// Serializes the previous proof container into length-prefixed bytes for payload chaining.
    pub fn bytes(&self, network_salt: &[u8; 32]) -> Vec<u8> {
        let prefix = b"vdf-prev-proof-v1";
        let capacity = network_salt.len()
            + prefix.len()
            + 32 // salt
            + 8 // kyn
            + 4 + self.drand_signature.len()
            + 8 // iterations
            + 4 + self.vdf_proof.proof_bytes.len()
            + 4 + self.identity_signature.len();

        let mut bytes = Vec::with_capacity(capacity);
        bytes.extend_from_slice(network_salt);
        bytes.extend_from_slice(prefix);
        bytes.extend_from_slice(&self.salt);
        bytes.extend_from_slice(&self.kyn.to_be_bytes());

        bytes.extend_from_slice(&(self.drand_signature.len() as u32).to_be_bytes());
        bytes.extend_from_slice(self.drand_signature.as_bytes());

        bytes.extend_from_slice(&self.iterations.to_be_bytes());

        bytes.extend_from_slice(&(self.vdf_proof.proof_bytes.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.vdf_proof.proof_bytes);

        bytes.extend_from_slice(&(self.identity_signature.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.identity_signature);

        bytes
    }

    /// Serializes the fields of the previous proof that are covered by its signature.
    ///
    /// # Security
    /// Enforces Cross-Network Replay Protection. By incorporating the 32-byte 
    /// `network_salt` and the literal `b"vdf-prev-v1"`, a previous proof signed for 
    /// the `.kin` network cannot be maliciously replayed on other networks.
    ///
    /// # Examples
    /// ```rust
    /// use kinetic_types::vdf::{PreviousProof, VdfProof};
    ///
    /// let prev = PreviousProof {
    ///     salt: [0u8; 32],
    ///     kyn: 12345,
    ///     drand_signature: "abcd".to_string(),
    ///     iterations: 1000,
    ///     vdf_proof: VdfProof { proof_bytes: vec![] },
    ///     signature: vec![],
    /// };
    /// let salt = [0x42; 32];
    /// let bytes = prev.signable_bytes(&salt);
    /// assert!(bytes.len() > 32);
    /// ```
    pub fn signable_bytes(&self, network_salt: &[u8; 32]) -> Vec<u8> {
        let prefix = b"vdf-prev-v1";
        let capacity = network_salt.len()
            + prefix.len()
            + 32 // salt
            + 8 // kyn
            + 4 + self.drand_signature.len()
            + 8 // iterations
            + 4 + self.vdf_proof.proof_bytes.len();

        let mut bytes = Vec::with_capacity(capacity);
        bytes.extend_from_slice(network_salt);
        bytes.extend_from_slice(prefix);
        bytes.extend_from_slice(&self.salt);
        bytes.extend_from_slice(&self.kyn.to_be_bytes());

        bytes.extend_from_slice(&(self.drand_signature.len() as u32).to_be_bytes());
        bytes.extend_from_slice(self.drand_signature.as_bytes());

        bytes.extend_from_slice(&self.iterations.to_be_bytes());

        bytes.extend_from_slice(&(self.vdf_proof.proof_bytes.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.vdf_proof.proof_bytes);

        bytes
    }
}

/// Revealed name registration payload submitted to the network during Phase 2.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Reveal {
    /// Protocol version indicator (default: `1`).
    #[serde(default = "default_protocol_version")]
    pub protocol_version: u8,
    /// Registered `.kin` name.
    pub name: String,
    /// Arbitrary name metadata or NRS zone record payload bytes.
    pub payload: Vec<u8>,
    /// 32-byte salt value for commitment blinding.
    pub salt: [u8; 32],
    /// Associated KineticTime kyn number.
    pub kyn: u64,
    /// Hex-encoded KineticTime BLS12-381 G2 signature.
    pub drand_signature: String,
    /// Number of VDF iterations completed.
    pub iterations: u64,
    /// Evaluated VDF proof.
    pub vdf_proof: VdfProof,
    /// Public key bytes of the name owner.
    #[serde(with = "crate::pubkey_serde::identity_serde")]
    pub pubkey: IdentityPubKey,
    /// Cryptographic signature over `signable_bytes` generated by the IdentityPrivKey.
    pub identity_signature: Vec<u8>,
    /// Optional delegated authorization proof for NRS zone updates.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub authorization: Option<Box<crate::identity::AuthorizedManifest>>,
    /// Optional chained proof for name renewal operations.
    pub previous_proof: Option<PreviousProof>,
}

impl Reveal {
    /// Serializes the reveal payload into a canonical byte string for cryptographic signature.
    ///
    /// # Security
    /// Enforces Cross-Network Replay Protection. By incorporating the 32-byte 
    /// `network_salt` and the literal `b"vdf-reveal-v1"`, a reveal record signed for 
    /// the `.kin` network cannot be maliciously replayed on other networks.
    ///
    /// # Examples
    /// ```rust
    /// use kinetic_types::vdf::{Reveal, VdfProof};
    ///
    /// let reveal = Reveal {
    ///     protocol_version: 1,
    ///     name: "example".to_string(),
    ///     payload: vec![],
    ///     salt: [0u8; 32],
    ///     kyn: 12345,
    ///     drand_signature: "abcd".to_string(),
    ///     iterations: 1000,
    ///     vdf_proof: VdfProof { proof_bytes: vec![] },
    ///     pubkey: vec![],
    ///     signature: vec![],
    ///     authorization: None,
    ///     previous_proof: None,
    /// };
    /// let salt = [0x42; 32];
    /// let bytes = reveal.signable_bytes(&salt);
    /// assert!(bytes.len() > 32);
    /// ```
    pub fn signable_bytes(&self, network_salt: &[u8; 32]) -> Vec<u8> {
        let prefix = b"vdf-reveal-v1";
        let prev_proof_bytes = self
            .previous_proof
            .as_ref()
            .map(|p| p.bytes(network_salt))
            .unwrap_or_default();

        let mut capacity = network_salt.len()
            + prefix.len()
            + 1 // protocol_version
            + 4 + self.name.len()
            + 4 + self.payload.len()
            + 32 // salt
            + 8 // kyn
            + 4 + self.drand_signature.len()
            + 8 // iterations
            + 4 + self.vdf_proof.proof_bytes.len()
            + 4 + self.pubkey.0.len()
            + 1; // previous_proof option flag

        if self.previous_proof.is_some() {
            capacity += 4 + prev_proof_bytes.len();
        }

        let mut bytes = Vec::with_capacity(capacity);
        bytes.extend_from_slice(network_salt);
        bytes.extend_from_slice(prefix);
        bytes.push(self.protocol_version);

        bytes.extend_from_slice(&(self.name.len() as u32).to_be_bytes());
        bytes.extend_from_slice(self.name.as_bytes());

        bytes.extend_from_slice(&(self.payload.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.payload);

        bytes.extend_from_slice(&self.salt);
        bytes.extend_from_slice(&self.kyn.to_be_bytes());

        bytes.extend_from_slice(&(self.drand_signature.len() as u32).to_be_bytes());
        bytes.extend_from_slice(self.drand_signature.as_bytes());

        bytes.extend_from_slice(&self.iterations.to_be_bytes());

        bytes.extend_from_slice(&(self.vdf_proof.proof_bytes.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.vdf_proof.proof_bytes);

        bytes.extend_from_slice(&(self.pubkey.0.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.pubkey.0);

        if self.previous_proof.is_some() {
            bytes.push(1);
            bytes.extend_from_slice(&(prev_proof_bytes.len() as u32).to_be_bytes());
            bytes.extend_from_slice(&prev_proof_bytes);
        } else {
            bytes.push(0);
        }

        bytes
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_previous_proof_serialization() {
        let prev = PreviousProof {
            salt: [2u8; 32],
            kyn: 12345,
            drand_signature: "deadbeef".to_string(),
            iterations: 1000,
            vdf_proof: VdfProof {
                proof_bytes: vec![1, 2, 3, 4],
            },
            identity_signature: vec![5, 6, 7],
        };
        let network_salt = &[9u8; 32];
        let bytes = prev.bytes(network_salt);

        // Assert domain separation prefix is included
        let prefix = b"vdf-prev-proof-v1";
        assert_eq!(&bytes[32..32 + prefix.len()], prefix);

        let signable = prev.signable_bytes(network_salt);
        let signable_prefix = b"vdf-prev-v1";
        assert_eq!(&signable[32..32 + signable_prefix.len()], signable_prefix);
    }
}
