//! Lightweight, no_std compatible cryptographic verification library for the Kinetic Network.
//! This crate contains the core verification logic, signatures, and data structures for Kinetic's VDF names, decoupled from the P2P networking stack.

pub mod error;

use serde::{Deserialize, Serialize};

/// Resquaring epoch interval in drand rounds (~6 months / 182.5 days at 3 seconds per round).
pub const RESQUARING_EPOCH_ROUNDS: u64 = 5_256_000;
/// Maximum allowed byte size for a domain reveal payload (64 KB).
pub const MAX_PAYLOAD_SIZE: usize = 65_536;

/// Cryptographic SHA-256 hash commitment to a registration request.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Commitment {
    /// 32-byte SHA-256 commitment hash.
    pub hash: [u8; 32],
}

/// Raw proof bytes generated by the chiavdf Verifiable Delay Function engine.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VdfProof {
    /// Raw VDF evaluation proof bytes.
    pub proof_bytes: Vec<u8>,
}

/// Initial commitment submission request payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommitRequest {
    /// Target `.kin` domain name.
    pub name: String,
    /// Cryptographic commitment.
    pub commitment: Commitment,
}

fn default_protocol_version() -> u8 {
    1
}

/// Previous VDF proof link in a chained domain renewal proof sequence.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct PreviousProof {
    /// 32-byte salt used in the previous proof generation.
    pub salt: [u8; 32],
    /// Associated drand randomness round number from prior registration.
    pub drand_pulse: u64,
    /// Hex-encoded drand BLS12-381 G2 signature from prior registration.
    pub drand_signature: String,
    /// Number of VDF iterations completed in prior registration.
    pub iterations: u64,
    /// Embedded VDF proof bytes.
    pub vdf_proof: VdfProof,
    /// Signature of the previous proof.
    pub signature: Vec<u8>,
}

impl PreviousProof {
    pub fn proof_bytes(&self, network_id: &str) -> Vec<u8> {
        let prefix_str = format!("{}-vdf-prev-v1", network_id);
        let prefix = prefix_str.as_bytes();
        let capacity = prefix.len()
            + 32 // salt
            + 8 // drand_pulse
            + 4 + self.drand_signature.len()
            + 8 // iterations
            + 4 + self.vdf_proof.proof_bytes.len()
            + 4 + self.signature.len();

        let mut bytes = Vec::with_capacity(capacity);
        bytes.extend_from_slice(prefix);
        bytes.extend_from_slice(&self.salt);
        bytes.extend_from_slice(&self.drand_pulse.to_be_bytes());

        bytes.extend_from_slice(&(self.drand_signature.len() as u32).to_be_bytes());
        bytes.extend_from_slice(self.drand_signature.as_bytes());

        bytes.extend_from_slice(&self.iterations.to_be_bytes());

        bytes.extend_from_slice(&(self.vdf_proof.proof_bytes.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.vdf_proof.proof_bytes);

        bytes.extend_from_slice(&(self.signature.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.signature);

        bytes
    }

    pub fn signable_bytes(&self, network_id: &str) -> Vec<u8> {
        let prefix_str = format!("{}-vdf-prev-v1", network_id);
        let prefix = prefix_str.as_bytes();
        let capacity = prefix.len()
            + 32 // salt
            + 8 // drand_pulse
            + 4 + self.drand_signature.len()
            + 8 // iterations
            + 4 + self.vdf_proof.proof_bytes.len();

        let mut bytes = Vec::with_capacity(capacity);
        bytes.extend_from_slice(prefix);
        bytes.extend_from_slice(&self.salt);
        bytes.extend_from_slice(&self.drand_pulse.to_be_bytes());

        bytes.extend_from_slice(&(self.drand_signature.len() as u32).to_be_bytes());
        bytes.extend_from_slice(self.drand_signature.as_bytes());

        bytes.extend_from_slice(&self.iterations.to_be_bytes());

        bytes.extend_from_slice(&(self.vdf_proof.proof_bytes.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.vdf_proof.proof_bytes);

        bytes
    }
}

/// Revealed domain registration payload submitted to the network during Phase 2.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Reveal {
    /// Protocol version indicator (default: `1`).
    #[serde(default = "default_protocol_version")]
    pub protocol_version: u8,
    /// Registered `.kin` domain name.
    pub name: String,
    /// Arbitrary domain metadata or DNS zone record payload bytes.
    pub payload: Vec<u8>,
    /// 32-byte salt value for commitment blinding.
    pub salt: [u8; 32],
    /// Associated drand randomness round number.
    pub drand_pulse: u64,
    /// Hex-encoded drand BLS12-381 G2 signature from the League of Entropy.
    pub drand_signature: String,
    /// Number of VDF iterations completed.
    pub iterations: u64,
    /// Evaluated VDF proof.
    pub vdf_proof: VdfProof,
    /// ML-DSA-65 public key of the domain owner.
    pub pubkey: Vec<u8>,
    /// ML-DSA-65 post-quantum signature over `signable_bytes`.
    pub signature: Vec<u8>,
    /// Optional chained proof for domain renewal operations.
    pub previous_proof: Option<PreviousProof>,
    /// Optional public key of the miner that computed the VDF proof.
    pub miner_pubkey: Option<Vec<u8>>,
}

impl Reveal {
    /// Verifies the ML-DSA-65 post-quantum signature over [`signable_bytes`](Reveal::signable_bytes).
    ///
    /// # Returns
    ///
    /// `Ok(())` if the signature is cryptographically valid for the embedded public key; an `error::VerifyError` otherwise.
    pub fn verify_signature(&self, network_id: &str) -> Result<(), error::VerifyError> {
        use ml_dsa::signature::Verifier;
        use ml_dsa::KeyInit;
        let signable = self.signable_bytes(network_id);

        let pubkey =
            ml_dsa::VerifyingKey::<ml_dsa::MlDsa65>::new_from_slice(self.pubkey.as_slice())
                .map_err(|_| error::VerifyError::MalformedPublicKey)?;

        let sig = ml_dsa::Signature::<ml_dsa::MlDsa65>::try_from(self.signature.as_slice())
            .map_err(|_| error::VerifyError::MalformedSignature)?;

        pubkey
            .verify(&signable, &sig)
            .map_err(|_| error::VerifyError::InvalidSignature)?;

        if let Some(prev) = &self.previous_proof {
            let prev_sig =
                ml_dsa::Signature::<ml_dsa::MlDsa65>::try_from(prev.signature.as_slice())
                    .map_err(|_| error::VerifyError::MalformedSignature)?;

            let prev_signable = prev.signable_bytes(network_id);
            pubkey
                .verify(&prev_signable, &prev_sig)
                .map_err(|_| error::VerifyError::InvalidSignature)?;
        }

        Ok(())
    }

    /// Serializes the reveal payload into a canonical byte string for ML-DSA-65 signature.
    pub fn signable_bytes(&self, network_id: &str) -> Vec<u8> {
        let prefix_str = format!("{}-vdf-reveal-v1", network_id);
        let prefix = prefix_str.as_bytes();
        let prev_proof_bytes = self
            .previous_proof
            .as_ref()
            .map(|p| p.proof_bytes(network_id))
            .unwrap_or_default();

        let mut capacity = prefix.len()
            + 1 // protocol_version
            + 4 + self.name.len()
            + 4 + self.payload.len()
            + 32 // salt
            + 8 // drand_pulse
            + 4 + self.drand_signature.len()
            + 8 // iterations
            + 4 + self.vdf_proof.proof_bytes.len()
            + 4 + self.pubkey.len()
            + 1; // previous_proof option flag

        if self.previous_proof.is_some() {
            capacity += 4 + prev_proof_bytes.len();
        }

        capacity += 1; // miner_pubkey option flag
        if let Some(miner_pk) = &self.miner_pubkey {
            capacity += 4 + miner_pk.len();
        }

        let mut bytes = Vec::with_capacity(capacity);
        bytes.extend_from_slice(prefix);
        bytes.push(self.protocol_version);

        bytes.extend_from_slice(&(self.name.len() as u32).to_be_bytes());
        bytes.extend_from_slice(self.name.as_bytes());

        bytes.extend_from_slice(&(self.payload.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.payload);

        bytes.extend_from_slice(&self.salt);
        bytes.extend_from_slice(&self.drand_pulse.to_be_bytes());

        bytes.extend_from_slice(&(self.drand_signature.len() as u32).to_be_bytes());
        bytes.extend_from_slice(self.drand_signature.as_bytes());

        bytes.extend_from_slice(&self.iterations.to_be_bytes());

        bytes.extend_from_slice(&(self.vdf_proof.proof_bytes.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.vdf_proof.proof_bytes);

        bytes.extend_from_slice(&(self.pubkey.len() as u32).to_be_bytes());
        bytes.extend_from_slice(&self.pubkey);

        if self.previous_proof.is_some() {
            bytes.push(1);
            bytes.extend_from_slice(&(prev_proof_bytes.len() as u32).to_be_bytes());
            bytes.extend_from_slice(&prev_proof_bytes);
        } else {
            bytes.push(0);
        }

        if let Some(miner_pk) = &self.miner_pubkey {
            bytes.push(1);
            bytes.extend_from_slice(&(miner_pk.len() as u32).to_be_bytes());
            bytes.extend_from_slice(miner_pk);
        } else {
            bytes.push(0);
        }

        bytes
    }
}

/// Request parameters for initiating a new VDF computation job.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VdfJobRequest {
    /// 32-byte target SHA-256 challenge commitment hash.
    pub challenge_hash: [u8; 32],
    /// Character length of the domain label being registered.
    pub name_length: u8,
    /// Evaluated Hashcash proof-of-work nonce.
    pub hashcash_nonce: u64,
    /// Associated drand randomness round number.
    pub drand_pulse: u64,
}
