[package]
name = "kinetic-primitives"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../README.md"
description = "Raw cryptographic mathematical operations (SHA-256, ML-DSA-65) for the Kinetic Network."
keywords = ["kinetic", "crypto", "ml-dsa", "sha2"]
categories = ["cryptography"]

[dependencies]
# --- Workspace Inherited ---
thiserror.workspace = true

# --- External Crates ---
ml-dsa = "0.1.1"
sha2.workspace = true
