//! Kinetic Time Cryptography & Branded Time Units.
//!
//! Provides branded time tracking for frontends, explorers, and node monitoring.
//! The underlying consensus engine uses the absolute KYN Provider, which this module
//! translates into the official Kinetic time hierarchy (The Crystal Lexicon) and
//! verifies via BLS12-381 Drand signatures.

use serde::{Deserialize, Serialize};
use drand_verify::Pubkey;

// Include constants generated by build.rs from network.json
include!(concat!(env!("OUT_DIR"), "/network_constants.rs"));

/// Strict type for Unix Time in seconds.
///
/// This wrapper prevents accidental math operations between network `Kyn` units 
/// and local wall-clock seconds.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct UTime(pub u64);

/// Strict type for an absolute Kinetic Network Time `Kyn`.
///
/// A `Kyn` represents a verified pulse from the network's KineticTime. 
/// Because it is mathematically proven, it is the only safe unit of time for 
/// protocol-level validation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Kyn(pub u64);

impl Kyn {
    /// Converts a `Kyn` number into a `UTime` (Unix epoch timestamp in seconds)
    /// using the network's strict genesis time and period.
    ///
    /// This is the secure method for deriving current time, as it bridges the 
    /// mathematical KineticTime into standard Unix time for interoperability 
    /// (e.g., verifying `expires_at` in Identity Documents).
    #[inline]
    pub fn to_utime(&self) -> UTime {
        UTime(DRAND_GENESIS_TIME.saturating_add(self.0.saturating_mul(DRAND_PERIOD)))
    }
}

impl UTime {
    /// Converts a `UTime` (Unix epoch timestamp in seconds) into an estimated `Kyn` number
    /// using the network's strict genesis time and period.
    #[inline]
    pub fn to_kyn(&self) -> Kyn {
        if DRAND_PERIOD == 0 {
            return Kyn(0);
        }
        // Integer division intentionally truncates sub-period remainder — if `unix_secs`
        // falls between two KineticTime rounds, this returns the floor (last confirmed) kyn.
        // This is the correct behavior for consensus: always use the last verified time.
        Kyn(self.0.saturating_sub(DRAND_GENESIS_TIME) / DRAND_PERIOD)
    }
}

/// A cryptographically verifiable pulse from the Drand oracle.
#[derive(Debug, Clone)]
pub struct DrandPulse {
    pub kyn: Kyn,
    pub signature: Vec<u8>,
}

impl DrandPulse {
    /// Cryptographically verifies the BLS signature of this pulse against the network's 
    /// hardcoded Drand public key. Performs zero network I/O.
    pub fn verify(&self) -> bool {
        // Fast fail on empty signatures
        if self.signature.is_empty() {
            return false;
        }
        if let Ok(pubkey) = drand_verify::G2PubkeyRfc::from_fixed(DRAND_PUBLIC_KEY_BYTES) {
            pubkey.verify(self.kyn.0, &[], &self.signature).unwrap_or(false)
        } else {
            false
        }
    }
}

/// Represents a specific point in time on the Kinetic network using branded units.
///
/// # Time Hierarchy
///
/// - **Kyn**: 3 seconds
/// - **Facet**: 1,200 Kyns (1 Hour)
/// - **Prism**: 28,800 Kyns (1 Day)
///
/// Higher-order units (Matrix = 7 Prisms, Lattice = 30 Prisms, Aeon = 365 Prisms)
/// are intentionally not provided as methods — callers derive them from `prism` directly.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct KineticTime {
    /// Number of completed 24-hour network Prisms (28,800 kyns each).
    pub prism: u64,
    /// Number of completed 1-hour network Facets within the current Prism (1,200 kyns each, 0..23).
    pub facet: u64,
    /// Number of completed 3-second Kyns within the current Facet (0..1199).
    pub kyn: u64,
    /// Total number of kyns elapsed since network genesis.
    pub total_kyns: u64,
}

impl KineticTime {
    /// Creates a new [`KineticTime`] instance from an absolute network kyn number.
    #[allow(clippy::absurd_extreme_comparisons)]
    pub fn from_kyn(current_kyn: Kyn, genesis_kyn: Kyn) -> Self {
        if current_kyn.0 < genesis_kyn.0 {
            return Self {
                prism: 0,
                facet: 0,
                kyn: 0,
                total_kyns: 0,
            };
        }

        let total_kyns = current_kyn.0 - genesis_kyn.0;

        let prism = total_kyns / 28_800;
        let remainder_after_prism = total_kyns % 28_800;

        let facet = remainder_after_prism / 1_200;
        let kyn = remainder_after_prism % 1_200;

        debug_assert!(facet < 24, "facet must be in 0..23, got {facet}");
        debug_assert!(kyn < 1_200, "kyn must be in 0..1199, got {kyn}");

        Self {
            prism,
            facet,
            kyn,
            total_kyns,
        }
    }
}
