#!/bin/bash
# Generates sitemap.xml, robots.txt, and llms.txt for the mdBook site

BASE_URL="https://saifmukhtar.github.io/kinetic"
SITEMAP_FILE="book/sitemap.xml"
ROBOTS_FILE="book/robots.txt"
LLMS_FILE="book/llms.txt"

# Ensure the book directory exists
mkdir -p book

# 1. Initialize sitemap.xml
echo '<?xml version="1.0" encoding="UTF-8"?>' > $SITEMAP_FILE
echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> $SITEMAP_FILE

# 2. Initialize robots.txt
echo "User-agent: *" > $ROBOTS_FILE
echo "Allow: /" >> $ROBOTS_FILE
echo "Sitemap: ${BASE_URL}/sitemap.xml" >> $ROBOTS_FILE

# 3. Initialize llms.txt
echo "# The Kinetic Protocol" > $LLMS_FILE
echo "> A stateless, Sybil-resistant naming system secured purely by math and time." >> $LLMS_FILE
echo "" >> $LLMS_FILE
echo "This file is optimized for AI agents and LLMs to easily scrape the Kinetic documentation." >> $LLMS_FILE
echo "" >> $LLMS_FILE
echo "## Documentation Pages" >> $LLMS_FILE

# Find all HTML files generated by mdBook and create entries
find book -name "*.html" -type f | sort | while read file; do
    # Remove the "book/" prefix to get the relative URL
    REL_URL=${file#book/}
    
    # Exclude 404.html from the indexing
    if [ "$REL_URL" = "404.html" ]; then
        continue
    fi

    FULL_URL="${BASE_URL}/${REL_URL}"

    # Append to sitemap.xml
    echo "  <url>" >> $SITEMAP_FILE
    echo "    <loc>${FULL_URL}</loc>" >> $SITEMAP_FILE
    LASTMOD=$(date -r "$file" "+%Y-%m-%dT%H:%M:%S%:z")
    echo "    <lastmod>${LASTMOD}</lastmod>" >> $SITEMAP_FILE
    echo "  </url>" >> $SITEMAP_FILE

    # Append to llms.txt
    PAGE_TITLE=$(basename "$REL_URL" .html | tr '_' ' ' | awk '{for(i=1;i<=NF;i++)sub(/./,toupper(substr($i,1,1)),$i)}1')
    echo "- [$PAGE_TITLE]($FULL_URL)" >> $LLMS_FILE
done

# Finalize sitemap.xml
echo '</urlset>' >> $SITEMAP_FILE

echo "Successfully generated:"
echo "- $SITEMAP_FILE"
echo "- $ROBOTS_FILE"
echo "- $LLMS_FILE"
