#!/bin/bash
# Generates a sitemap.xml for the mdBook site

BASE_URL="https://saifmukhtar.github.io/kinetic"
OUTPUT_FILE="book/sitemap.xml"

# Ensure the book directory exists
mkdir -p book

echo '<?xml version="1.0" encoding="UTF-8"?>' > $OUTPUT_FILE
echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> $OUTPUT_FILE

# Find all HTML files generated by mdBook and create sitemap entries
find book -name "*.html" -type f | while read file; do
    # Remove the "book/" prefix to get the relative URL
    REL_URL=${file#book/}
    
    # Exclude 404.html from the sitemap
    if [ "$REL_URL" = "404.html" ]; then
        continue
    fi

    # Print the entry
    echo "  <url>" >> $OUTPUT_FILE
    echo "    <loc>${BASE_URL}/${REL_URL}</loc>" >> $OUTPUT_FILE
    # Use the file's modification time as lastmod
    LASTMOD=$(date -r "$file" "+%Y-%m-%dT%H:%M:%S%:z")
    echo "    <lastmod>${LASTMOD}</lastmod>" >> $OUTPUT_FILE
    echo "  </url>" >> $OUTPUT_FILE
done

echo '</urlset>' >> $OUTPUT_FILE

echo "Sitemap generated at $OUTPUT_FILE"
