[package]
name = "kinetic-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "kinetic"
path = "src/main.rs"

[features]
simulation = ["kinetic-core/simulation", "kinetic-kid/simulation"]

[dependencies]
anyhow.workspace = true
clap = { version = "4.6.1", features = ["derive"] }
directories = "6.0.0"
ed25519-dalek = "2.2.0"
getrandom = "0.4.3"
hex = "0.4.3"
bip39 = "2.2.2"
kinetic-core = { version = "0.2.0", path = "../kinetic-core" }
kinetic-local = { version = "0.2.0", path = "../kinetic-local" }
kinetic-network = { version = "0.2.0", path = "../kinetic-network" }
kinetic-vdf-rsa = { path = "../kinetic-vdf-rsa" }
kinetic-kid = { version = "0.2.0", path = "../kinetic-kid" }
kinetic-primitives = { path = "../kinetic-primitives" }
libp2p = { version = "0.53", features = ["ed25519"] }
rand = "0.10.1"
rand_core = { version = "0.6.4", features = ["std", "getrandom"] }
base64 = "0.22"
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
sha2 = "0.11.0"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing.workspace = true
tracing-subscriber.workspace = true
dirs = "6.0.0"
rpassword = "7"
rand_chacha = "0.10.0"

data-encoding = "2.11.0"
bincode = "1.3.3"

[dev-dependencies]
axum = "0.8.9"
tokio.workspace = true
mockito = "1.7.2"
tempfile = "3"

