name: Continuous Integration

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/ci.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Check & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
      - name: Enable longpaths (Windows)
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install MPIR (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd kinetic-vdf/chiavdf
          git clone https://github.com/Chia-Network/mpir_gc_x64.git

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libgmp-dev clang libclang-dev

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install gmp

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Formatting (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: cargo fmt --all -- --check

      - name: Run Clippy Lints (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Run Tests (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: cargo test --workspace

      - name: Check Compilation (Windows & macOS)
        if: matrix.os != 'ubuntu-latest'
        run: cargo check --workspace --tests
