name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Format, Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy Lints
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Run Tests
        run: cargo test --workspace
