[package]
name = "kinetic-vdf-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
kinetic-core = { path = "../../kinetic-core" }

[dependencies.kinetic-vdf]
path = ".."

[[bin]]
name = "fuzz_vdf_verify"
path = "fuzz_targets/fuzz_vdf_verify.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_vdf_evaluate"
path = "fuzz_targets/fuzz_vdf_evaluate.rs"
test = false
doc = false
bench = false
